"""Parte 7 — Paradigmas (clases 107-122). Reutiliza gen_parte3.write_class."""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import gen_parte3 as g3  # noqa: E402

S = {}

S[107] = {
    "descripcion": "Sumar los enteros de 1 a n, como ejemplo mínimo para hablar de paradigmas.",
    "objetivo": "Entender qué es un **paradigma**: una forma de estructurar la solución (imperativa, funcional, declarativa…). El mismo problema —sumar 1 a n— puede resolverse de varias maneras según el paradigma.",
    "resultados": ["Definir qué es un paradigma.", "Reconocer que un problema admite varios enfoques.", "Situar los paradigmas del curso."],
    "temas": [("Paradigma", "Forma de estructurar la solución"), ("Multiparadigma", "Un lenguaje puede ofrecer varios"), ("Mismo problema, varios enfoques", "Imperativo, funcional, declarativo")],
    "definiciones": [("Paradigma", "estilo de estructurar programas (imperativo, OO, funcional, declarativo). Clave: cambia cómo se piensa."), ("Multiparadigma", "lenguaje que soporta varios estilos (Python, C#, Rust). Clave: eliges por problema."), ("Enfoque", "la estrategia elegida para resolver. Clave: distintos paradigmas, distinta forma.")],
    "situacion": "Sumar 1..n se puede hacer con un bucle (imperativo), con reduce (funcional) o con una fórmula/consulta (declarativo). El paradigma decide la forma, no el resultado.",
    "entrada": "un entero `n` (n >= 1)",
    "salida": "`suma=<1+2+...+n>`",
    "formula": "suma = 1 + 2 + ... + n",
    "algoritmo": "LEER n ; sumar 1..n ; ESCRIBIR suma",
    "casos": [("5", "suma=15"), ("3", "suma=6"), ("1", "suma=1")],
    "comparacion": [("Sintáctica", "Bucle, `reduce` o fórmula según el estilo."), ("Semántica", "Todos dan el mismo resultado; cambia la estructura."), ("Paradigmática", "Imperativo describe pasos; declarativo describe el resultado.")],
    "familia": "Casi todos los lenguajes del núcleo son multiparadigma: permiten el mismo problema de varias formas.",
    "errores": [("Creer que hay un solo modo correcto", "encasillarse en un paradigma", "elegir el que mejor exprese el problema"), ("Confundir paradigma con lenguaje", "un lenguaje ofrece varios", "distinguir el estilo del lenguaje")],
    "faq": [("¿Cuál es mejor?", "Depende del problema: cada paradigma brilla en distintos casos."), ("¿Un lenguaje = un paradigma?", "No: la mayoría son multiparadigma.")],
    "reto": "Resuelve la misma suma con una fórmula cerrada (n·(n+1)/2) y compárala; resuélvelo en **Python**.",
    "impls": {
        "python": "import sys\n\nn = int(sys.stdin.readline())\nsuma = sum(range(1, n + 1))\nprint(f\"suma={suma}\")\n",
        "javascript": "import { readFileSync } from \"node:fs\";\n\nconst n = parseInt(readFileSync(0, \"utf8\").trim(), 10);\nlet suma = 0;\nfor (let i = 1; i <= n; i++) suma += i;\nconsole.log(`suma=${suma}`);\n",
        "typescript": "import { readFileSync } from \"node:fs\";\n\nconst n: number = parseInt(readFileSync(0, \"utf8\").trim(), 10);\nlet suma = 0;\nfor (let i = 1; i <= n; i++) suma += i;\nconsole.log(`suma=${suma}`);\n",
        "java": "import java.io.BufferedReader;\nimport java.io.IOException;\nimport java.io.InputStreamReader;\n\npublic class Main {\n    public static void main(String[] args) throws IOException {\n        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));\n        int n = Integer.parseInt(br.readLine().trim());\n        long suma = 0;\n        for (int i = 1; i <= n; i++) suma += i;\n        System.out.println(\"suma=\" + suma);\n    }\n}\n",
        "csharp": "using System;\n\nint n = int.Parse(Console.In.ReadToEnd().Trim());\nlong suma = 0;\nfor (int i = 1; i <= n; i++) suma += i;\nConsole.WriteLine($\"suma={suma}\");\n",
        "go": "package main\n\nimport (\n\t\"bufio\"\n\t\"fmt\"\n\t\"os\"\n\t\"strconv\"\n\t\"strings\"\n)\n\nfunc main() {\n\tline, _ := bufio.NewReader(os.Stdin).ReadString('\\n')\n\tn, _ := strconv.Atoi(strings.TrimSpace(line))\n\tsuma := 0\n\tfor i := 1; i <= n; i++ {\n\t\tsuma += i\n\t}\n\tfmt.Printf(\"suma=%d\\n\", suma)\n}\n",
        "rust": "use std::io::Read;\n\nfn main() {\n    let mut s = String::new();\n    std::io::stdin().read_to_string(&mut s).unwrap();\n    let n: i64 = s.trim().parse().unwrap();\n    let suma: i64 = (1..=n).sum();\n    println!(\"suma={suma}\");\n}\n",
        "c": "#include <stdio.h>\n\nint main(void) {\n    long n;\n    if (scanf(\"%ld\", &n) != 1) return 1;\n    long suma = 0;\n    for (long i = 1; i <= n; i++) suma += i;\n    printf(\"suma=%ld\\n\", suma);\n    return 0;\n}\n",
        "php": "<?php\n$n = (int) trim(fgets(STDIN));\n$suma = 0;\nfor ($i = 1; $i <= $n; $i++) {\n    $suma += $i;\n}\necho \"suma=$suma\\n\";\n",
        "sql": "-- SQL (declarativo): suma con CTE recursivo (ilustrativo, n=5).\nWITH RECURSIVE r(i) AS (VALUES (1) UNION ALL SELECT i + 1 FROM r WHERE i < 5)\nSELECT printf('suma=%d', sum(i)) AS resultado FROM r;\n",
    },
}

S[108] = {
    "descripcion": "Sumar una lista de enteros con un estilo imperativo: un acumulador y un bucle explícito.",
    "objetivo": "Practicar el **paradigma imperativo y estructurado**: describir la solución como una secuencia de pasos que modifican el estado (un acumulador), usando bucles y condiciones.",
    "resultados": ["Resolver con estado mutable y bucles.", "Reconocer la secuencia de pasos.", "Contrastar con el estilo funcional."],
    "temas": [("Imperativo", "Pasos que cambian el estado"), ("Estructurado", "Secuencia, selección, iteración"), ("Estado mutable", "Variables que cambian")],
    "definiciones": [("Imperativo", "paradigma que describe cómo cambiar el estado paso a paso. Clave: bucles y asignaciones."), ("Estructurado", "usa solo secuencia, selección e iteración (sin goto). Clave: código claro."), ("Estado mutable", "variables que cambian durante la ejecución. Clave: el acumulador.")],
    "situacion": "El estilo imperativo es el más cercano a cómo funciona la máquina: 'haz esto, luego esto'. Sumar con un acumulador y un bucle es su ejemplo puro.",
    "entrada": "una línea con enteros separados por espacio",
    "salida": "`suma=<suma de todos>`",
    "formula": "acumular la suma recorriendo la lista",
    "algoritmo": "suma <- 0 ; PARA CADA x: suma <- suma + x",
    "casos": [("1 2 3", "suma=6"), ("5", "suma=5"), ("10 20", "suma=30")],
    "comparacion": [("Sintáctica", "Bucle explícito en todos los imperativos."), ("Semántica", "Modifica un acumulador; el estado evoluciona."), ("Paradigmática", "El funcional evitaría el acumulador mutable con reduce.")],
    "familia": "Casi todos los lenguajes del núcleo soportan el estilo imperativo de forma nativa.",
    "errores": [("No inicializar el acumulador", "resultado incorrecto", "empezar en 0"), ("Efectos secundarios ocultos", "estado difícil de seguir", "mantener el estado local y claro")],
    "faq": [("¿Imperativo o funcional?", "Imperativo es directo y eficiente; funcional es más declarativo. Depende."), ("¿Estructurado significa sin goto?", "Sí: solo secuencia, selección e iteración.")],
    "reto": "Suma solo los mayores que 2 con el mismo estilo imperativo; resuélvelo en **C**.",
    "impls": {
        "python": "import sys\n\nnums = [int(x) for x in sys.stdin.read().split()]\nsuma = 0\nfor x in nums:\n    suma += x\nprint(f\"suma={suma}\")\n",
        "javascript": "import { readFileSync } from \"node:fs\";\n\nconst nums = readFileSync(0, \"utf8\").trim().split(/\\s+/).map(Number);\nlet suma = 0;\nfor (const x of nums) suma += x;\nconsole.log(`suma=${suma}`);\n",
        "typescript": "import { readFileSync } from \"node:fs\";\n\nconst nums: number[] = readFileSync(0, \"utf8\").trim().split(/\\s+/).map(Number);\nlet suma = 0;\nfor (const x of nums) suma += x;\nconsole.log(`suma=${suma}`);\n",
        "java": "import java.io.BufferedReader;\nimport java.io.IOException;\nimport java.io.InputStreamReader;\n\npublic class Main {\n    public static void main(String[] args) throws IOException {\n        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));\n        String[] p = br.readLine().trim().split(\"\\\\s+\");\n        long suma = 0;\n        for (String s : p) suma += Integer.parseInt(s);\n        System.out.println(\"suma=\" + suma);\n    }\n}\n",
        "csharp": "using System;\n\nstring[] p = Console.In.ReadToEnd()\n    .Split(new[] { ' ', '\\t', '\\n', '\\r' }, StringSplitOptions.RemoveEmptyEntries);\nlong suma = 0;\nforeach (string s in p) suma += int.Parse(s);\nConsole.WriteLine($\"suma={suma}\");\n",
        "go": "package main\n\nimport (\n\t\"bufio\"\n\t\"fmt\"\n\t\"os\"\n\t\"strconv\"\n\t\"strings\"\n)\n\nfunc main() {\n\tline, _ := bufio.NewReader(os.Stdin).ReadString('\\n')\n\tsuma := 0\n\tfor _, s := range strings.Fields(line) {\n\t\tn, _ := strconv.Atoi(s)\n\t\tsuma += n\n\t}\n\tfmt.Printf(\"suma=%d\\n\", suma)\n}\n",
        "rust": "use std::io::Read;\n\nfn main() {\n    let mut s = String::new();\n    std::io::stdin().read_to_string(&mut s).unwrap();\n    let mut suma: i64 = 0;\n    for x in s.split_whitespace() {\n        suma += x.parse::<i64>().unwrap();\n    }\n    println!(\"suma={suma}\");\n}\n",
        "c": "#include <stdio.h>\n\nint main(void) {\n    long suma = 0, x;\n    while (scanf(\"%ld\", &x) == 1) suma += x;\n    printf(\"suma=%ld\\n\", suma);\n    return 0;\n}\n",
        "php": "<?php\n$nums = preg_split('/\\s+/', trim(fgets(STDIN)));\n$suma = 0;\nforeach ($nums as $x) {\n    $suma += (int) $x;\n}\necho \"suma=$suma\\n\";\n",
        "sql": "-- SQL: SUM() agrega sobre filas.\nWITH nums(x) AS (VALUES (1), (2), (3))\nSELECT printf('suma=%d', sum(x)) AS resultado FROM nums;\n",
    },
}

S[109] = {
    "descripcion": "Calcular el promedio (división entera) de una lista usando un procedimiento reutilizable.",
    "objetivo": "Practicar el **paradigma procedimental y modular**: descomponer el programa en procedimientos con nombre que se llaman entre sí. Es el imperativo organizado en unidades reutilizables.",
    "resultados": ["Encapsular un cálculo en un procedimiento.", "Llamarlo desde el programa principal.", "Reconocer la modularidad procedimental."],
    "temas": [("Procedimiento", "Bloque con nombre reutilizable"), ("Modularidad", "Dividir en unidades"), ("Reutilización", "Llamar en vez de repetir")],
    "definiciones": [("Procedimental", "paradigma que organiza el código en procedimientos/funciones. Clave: imperativo modular."), ("Procedimiento", "unidad con nombre que realiza una tarea. Clave: se invoca cuando se necesita."), ("Modularidad", "dividir el problema en piezas manejables. Clave: cada una con una responsabilidad.")],
    "situacion": "En vez de un `main` gigante, se define `promedio(lista)` y se llama. El estilo procedimental (C, Pascal) organiza el imperativo en procedimientos.",
    "entrada": "una línea con enteros separados por espacio",
    "salida": "`promedio=<suma dividida entre la cantidad, entera>`",
    "formula": "promedio = suma / cantidad (división entera)",
    "algoritmo": "PROCEDIMIENTO promedio(lista): DEVOLVER suma(lista)/|lista|",
    "casos": [("2 4 6", "promedio=4"), ("10", "promedio=10"), ("3 5", "promedio=4")],
    "comparacion": [("Sintáctica", "Cada lenguaje define el procedimiento a su manera."), ("Semántica", "El procedimiento agrupa pasos imperativos bajo un nombre."), ("Paradigmática", "SQL usa AVG (declarativo).")],
    "familia": "C y Pascal son los ejemplos clásicos del estilo procedimental; casi todos lo soportan.",
    "errores": [("Dividir sin controlar cantidad 0", "división por cero", "aquí siempre hay elementos"), ("Todo en el main", "sin modularidad", "extraer procedimientos con responsabilidad clara")],
    "faq": [("¿Procedimiento o función?", "Un procedimiento actúa; una función devuelve valor. Aquí devolvemos el promedio."), ("¿Procedimental es viejo?", "Es la base; sigue vigente y presente en todos los lenguajes.")],
    "reto": "Añade un procedimiento `maximo` y muéstralo también; resuélvelo en **Go**.",
    "impls": {
        "python": "import sys\n\n\ndef promedio(lista):\n    return sum(lista) // len(lista)\n\n\nnums = [int(x) for x in sys.stdin.read().split()]\nprint(f\"promedio={promedio(nums)}\")\n",
        "javascript": "import { readFileSync } from \"node:fs\";\n\nfunction promedio(lista) {\n  const suma = lista.reduce((a, b) => a + b, 0);\n  return Math.trunc(suma / lista.length);\n}\n\nconst nums = readFileSync(0, \"utf8\").trim().split(/\\s+/).map(Number);\nconsole.log(`promedio=${promedio(nums)}`);\n",
        "typescript": "import { readFileSync } from \"node:fs\";\n\nfunction promedio(lista: number[]): number {\n  const suma = lista.reduce((a, b) => a + b, 0);\n  return Math.trunc(suma / lista.length);\n}\n\nconst nums: number[] = readFileSync(0, \"utf8\").trim().split(/\\s+/).map(Number);\nconsole.log(`promedio=${promedio(nums)}`);\n",
        "java": "import java.io.BufferedReader;\nimport java.io.IOException;\nimport java.io.InputStreamReader;\n\npublic class Main {\n    static long promedio(int[] a) {\n        long suma = 0;\n        for (int x : a) suma += x;\n        return suma / a.length;\n    }\n\n    public static void main(String[] args) throws IOException {\n        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));\n        String[] p = br.readLine().trim().split(\"\\\\s+\");\n        int[] nums = new int[p.length];\n        for (int i = 0; i < p.length; i++) nums[i] = Integer.parseInt(p[i]);\n        System.out.println(\"promedio=\" + promedio(nums));\n    }\n}\n",
        "csharp": "using System;\nusing System.Linq;\n\nlong Promedio(int[] a) => a.Sum(x => (long) x) / a.Length;\n\nint[] nums = Console.In.ReadToEnd()\n    .Split(new[] { ' ', '\\t', '\\n', '\\r' }, StringSplitOptions.RemoveEmptyEntries)\n    .Select(int.Parse).ToArray();\nConsole.WriteLine($\"promedio={Promedio(nums)}\");\n",
        "go": "package main\n\nimport (\n\t\"bufio\"\n\t\"fmt\"\n\t\"os\"\n\t\"strconv\"\n\t\"strings\"\n)\n\nfunc promedio(a []int) int {\n\tsuma := 0\n\tfor _, x := range a {\n\t\tsuma += x\n\t}\n\treturn suma / len(a)\n}\n\nfunc main() {\n\tline, _ := bufio.NewReader(os.Stdin).ReadString('\\n')\n\tvar nums []int\n\tfor _, s := range strings.Fields(line) {\n\t\tn, _ := strconv.Atoi(s)\n\t\tnums = append(nums, n)\n\t}\n\tfmt.Printf(\"promedio=%d\\n\", promedio(nums))\n}\n",
        "rust": "use std::io::Read;\n\nfn promedio(a: &[i64]) -> i64 {\n    let suma: i64 = a.iter().sum();\n    suma / a.len() as i64\n}\n\nfn main() {\n    let mut s = String::new();\n    std::io::stdin().read_to_string(&mut s).unwrap();\n    let nums: Vec<i64> = s.split_whitespace().map(|x| x.parse().unwrap()).collect();\n    println!(\"promedio={}\", promedio(&nums));\n}\n",
        "c": "#include <stdio.h>\n\nint main(void) {\n    long v[1024];\n    int n = 0;\n    while (scanf(\"%ld\", &v[n]) == 1) n++;\n    long suma = 0;\n    for (int i = 0; i < n; i++) suma += v[i];\n    printf(\"promedio=%ld\\n\", suma / n);\n    return 0;\n}\n",
        "php": "<?php\nfunction promedio($a) {\n    return intdiv(array_sum($a), count($a));\n}\n\n$nums = array_map('intval', preg_split('/\\s+/', trim(fgets(STDIN))));\necho \"promedio=\" . promedio($nums) . \"\\n\";\n",
        "sql": "-- SQL: AVG con división entera.\nWITH nums(x) AS (VALUES (2), (4), (6))\nSELECT printf('promedio=%d', sum(x) / count(*)) AS resultado FROM nums;\n",
    },
}

S[110] = {
    "descripcion": "Crear un objeto Contador y aumentarlo n veces, mostrando su estado final.",
    "objetivo": "Practicar el paradigma **orientado a objetos**: agrupar estado (datos) y comportamiento (métodos) en objetos. Un contador con su método `incrementar` es el ejemplo mínimo de estado encapsulado.",
    "resultados": ["Definir una clase con estado y métodos.", "Crear un objeto y cambiar su estado.", "Reconocer la unión de datos y comportamiento."],
    "temas": [("Clase y objeto", "Molde e instancia"), ("Estado", "Datos del objeto"), ("Método", "Comportamiento que actúa sobre el estado")],
    "definiciones": [("Objeto", "instancia que agrupa estado y comportamiento. Clave: datos + métodos juntos."), ("Clase", "molde que define objetos. Clave: describe estado y métodos."), ("Método", "función asociada a un objeto que opera sobre su estado. Clave: `contador.incrementar()`.")],
    "situacion": "Un carrito de compra, una cuenta, un contador: la OO modela entidades con estado que evoluciona mediante métodos. El objeto recuerda su estado entre llamadas.",
    "entrada": "un entero `n` (número de incrementos)",
    "salida": "`cuenta=<n>`",
    "formula": "contador incrementado n veces desde 0",
    "algoritmo": "c <- Contador() ; REPETIR n veces: c.incrementar() ; ESCRIBIR c.cuenta",
    "casos": [("5", "cuenta=5"), ("0", "cuenta=0"), ("3", "cuenta=3")],
    "comparacion": [("Sintáctica", "`class` (Python/Java/C#/PHP), `struct`+métodos (Go/Rust), objeto (JS)."), ("Semántica", "El objeto conserva su estado entre llamadas a métodos."), ("Paradigmática", "SQL no tiene objetos con estado; opera sobre datos.")],
    "familia": "En Ruby todo es un objeto. En Go/Rust no hay clases, pero structs con métodos cumplen el rol.",
    "errores": [("Estado compartido sin control", "objetos que se pisan", "encapsular el estado en cada objeto"), ("Confundir clase con objeto", "molde vs. instancia", "la clase define; el objeto existe")],
    "faq": [("¿Todo debe ser objeto?", "No: la OO es una herramienta; a veces una función basta."), ("¿Go tiene clases?", "No, pero structs con métodos ofrecen lo esencial de la OO.")],
    "reto": "Añade un método `decrementar` y aplícalo; resuélvelo en **Rust** con un struct.",
    "impls": {
        "python": "import sys\n\n\nclass Contador:\n    def __init__(self):\n        self.cuenta = 0\n\n    def incrementar(self):\n        self.cuenta += 1\n\n\nn = int(sys.stdin.readline())\nc = Contador()\nfor _ in range(n):\n    c.incrementar()\nprint(f\"cuenta={c.cuenta}\")\n",
        "javascript": "import { readFileSync } from \"node:fs\";\n\nclass Contador {\n  constructor() {\n    this.cuenta = 0;\n  }\n  incrementar() {\n    this.cuenta++;\n  }\n}\n\nconst n = parseInt(readFileSync(0, \"utf8\").trim(), 10);\nconst c = new Contador();\nfor (let i = 0; i < n; i++) c.incrementar();\nconsole.log(`cuenta=${c.cuenta}`);\n",
        "typescript": "import { readFileSync } from \"node:fs\";\n\nclass Contador {\n  cuenta = 0;\n  incrementar(): void {\n    this.cuenta++;\n  }\n}\n\nconst n: number = parseInt(readFileSync(0, \"utf8\").trim(), 10);\nconst c = new Contador();\nfor (let i = 0; i < n; i++) c.incrementar();\nconsole.log(`cuenta=${c.cuenta}`);\n",
        "java": "import java.io.BufferedReader;\nimport java.io.IOException;\nimport java.io.InputStreamReader;\n\npublic class Main {\n    static class Contador {\n        int cuenta = 0;\n        void incrementar() { cuenta++; }\n    }\n\n    public static void main(String[] args) throws IOException {\n        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));\n        int n = Integer.parseInt(br.readLine().trim());\n        Contador c = new Contador();\n        for (int i = 0; i < n; i++) c.incrementar();\n        System.out.println(\"cuenta=\" + c.cuenta);\n    }\n}\n",
        "csharp": "using System;\n\nint n = int.Parse(Console.In.ReadToEnd().Trim());\nvar c = new Contador();\nfor (int i = 0; i < n; i++) c.Incrementar();\nConsole.WriteLine($\"cuenta={c.Cuenta}\");\n\nclass Contador {\n    public int Cuenta { get; private set; }\n    public void Incrementar() => Cuenta++;\n}\n",
        "go": "package main\n\nimport (\n\t\"bufio\"\n\t\"fmt\"\n\t\"os\"\n\t\"strconv\"\n\t\"strings\"\n)\n\ntype Contador struct {\n\tcuenta int\n}\n\nfunc (c *Contador) incrementar() {\n\tc.cuenta++\n}\n\nfunc main() {\n\tline, _ := bufio.NewReader(os.Stdin).ReadString('\\n')\n\tn, _ := strconv.Atoi(strings.TrimSpace(line))\n\tc := &Contador{}\n\tfor i := 0; i < n; i++ {\n\t\tc.incrementar()\n\t}\n\tfmt.Printf(\"cuenta=%d\\n\", c.cuenta)\n}\n",
        "rust": "use std::io::Read;\n\nstruct Contador {\n    cuenta: i64,\n}\n\nimpl Contador {\n    fn nuevo() -> Self {\n        Contador { cuenta: 0 }\n    }\n    fn incrementar(&mut self) {\n        self.cuenta += 1;\n    }\n}\n\nfn main() {\n    let mut s = String::new();\n    std::io::stdin().read_to_string(&mut s).unwrap();\n    let n: i64 = s.trim().parse().unwrap();\n    let mut c = Contador::nuevo();\n    for _ in 0..n {\n        c.incrementar();\n    }\n    println!(\"cuenta={}\", c.cuenta);\n}\n",
        "c": "#include <stdio.h>\n\nstruct Contador {\n    long cuenta;\n};\n\nvoid incrementar(struct Contador *c) {\n    c->cuenta++;\n}\n\nint main(void) {\n    long n;\n    if (scanf(\"%ld\", &n) != 1) return 1;\n    struct Contador c = {0};\n    for (long i = 0; i < n; i++) incrementar(&c);\n    printf(\"cuenta=%ld\\n\", c.cuenta);\n    return 0;\n}\n",
        "php": "<?php\nclass Contador {\n    public int $cuenta = 0;\n    public function incrementar() {\n        $this->cuenta++;\n    }\n}\n\n$n = (int) trim(fgets(STDIN));\n$c = new Contador();\nfor ($i = 0; $i < $n; $i++) {\n    $c->incrementar();\n}\necho \"cuenta={$c->cuenta}\\n\";\n",
        "sql": "-- SQL no tiene objetos con estado; el contador es el propio valor.\nWITH nums(n) AS (VALUES (5), (0), (3))\nSELECT printf('cuenta=%d', n) AS resultado FROM nums;\n",
    },
}

S[111] = {
    "descripcion": "Dado el tipo de animal, producir su sonido mediante polimorfismo.",
    "objetivo": "Practicar **herencia, composición y polimorfismo**: distintos tipos que comparten una interfaz común (`sonido`) y responden cada uno a su manera. Llamar al mismo método da resultados distintos según el tipo real.",
    "resultados": ["Reconocer el polimorfismo (mismo método, distinto comportamiento).", "Distinguir herencia de composición.", "Despachar según el tipo real."],
    "temas": [("Herencia", "Un tipo deriva de otro"), ("Polimorfismo", "Mismo método, comportamiento distinto"), ("Composición", "Construir con partes, alternativa a heredar")],
    "definiciones": [("Herencia", "un tipo hereda estado/comportamiento de otro. Clave: reutiliza y especializa."), ("Polimorfismo", "el mismo método se comporta distinto según el tipo real. Clave: `animal.sonido()`."), ("Composición", "construir un objeto a partir de otros (tiene-un) en vez de heredar (es-un). Clave: más flexible.")],
    "situacion": "Perro, gato y vaca son animales, pero cada uno suena distinto. El polimorfismo permite tratarlos igual (`animal.sonido()`) y obtener la respuesta correcta según el tipo.",
    "entrada": "una palabra: `perro`, `gato` o `vaca`",
    "salida": "`sonido=<guau|miau|muu>`",
    "formula": "cada tipo devuelve su propio sonido",
    "algoritmo": "LEER tipo ; crear animal ; ESCRIBIR animal.sonido()",
    "casos": [("perro", "sonido=guau"), ("gato", "sonido=miau"), ("vaca", "sonido=muu")],
    "comparacion": [("Sintáctica", "Herencia/interfaces (Java/C#), traits (Rust), interfaces (Go), duck typing (Python/JS)."), ("Semántica", "El despacho es dinámico: se decide en ejecución por el tipo real."), ("Paradigmática", "SQL usa CASE; no hay despacho polimórfico.")],
    "familia": "En Ruby el polimorfismo es por duck typing. En Kotlin, interfaces y clases selladas.",
    "errores": [("Abusar de la herencia profunda", "jerarquías frágiles", "preferir composición cuando encaje"), ("Olvidar un tipo", "caso sin manejar", "cubrir todos o usar un default")],
    "faq": [("¿Herencia o composición?", "Composición por defecto; herencia cuando hay un 'es-un' real y estable."), ("¿Qué es duck typing?", "Si suena como pato, es pato: importa el método, no el tipo declarado.")],
    "reto": "Añade un animal `pato` y su sonido, y resuélvelo en **Go** con una interfaz.",
    "impls": {
        "python": "import sys\n\n\nclass Perro:\n    def sonido(self):\n        return \"guau\"\n\n\nclass Gato:\n    def sonido(self):\n        return \"miau\"\n\n\nclass Vaca:\n    def sonido(self):\n        return \"muu\"\n\n\ntipo = sys.stdin.readline().strip()\nanimales = {\"perro\": Perro(), \"gato\": Gato(), \"vaca\": Vaca()}\nprint(f\"sonido={animales[tipo].sonido()}\")\n",
        "javascript": "import { readFileSync } from \"node:fs\";\n\nclass Perro { sonido() { return \"guau\"; } }\nclass Gato { sonido() { return \"miau\"; } }\nclass Vaca { sonido() { return \"muu\"; } }\n\nconst tipo = readFileSync(0, \"utf8\").trim();\nconst animales = { perro: new Perro(), gato: new Gato(), vaca: new Vaca() };\nconsole.log(`sonido=${animales[tipo].sonido()}`);\n",
        "typescript": "import { readFileSync } from \"node:fs\";\n\ninterface Animal { sonido(): string; }\nclass Perro implements Animal { sonido() { return \"guau\"; } }\nclass Gato implements Animal { sonido() { return \"miau\"; } }\nclass Vaca implements Animal { sonido() { return \"muu\"; } }\n\nconst tipo: string = readFileSync(0, \"utf8\").trim();\nconst animales: Record<string, Animal> = { perro: new Perro(), gato: new Gato(), vaca: new Vaca() };\nconsole.log(`sonido=${animales[tipo].sonido()}`);\n",
        "java": "import java.io.BufferedReader;\nimport java.io.IOException;\nimport java.io.InputStreamReader;\n\npublic class Main {\n    interface Animal { String sonido(); }\n    static class Perro implements Animal { public String sonido() { return \"guau\"; } }\n    static class Gato implements Animal { public String sonido() { return \"miau\"; } }\n    static class Vaca implements Animal { public String sonido() { return \"muu\"; } }\n\n    public static void main(String[] args) throws IOException {\n        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));\n        String tipo = br.readLine().trim();\n        Animal a;\n        switch (tipo) {\n            case \"perro\": a = new Perro(); break;\n            case \"gato\": a = new Gato(); break;\n            default: a = new Vaca();\n        }\n        System.out.println(\"sonido=\" + a.sonido());\n    }\n}\n",
        "csharp": "using System;\n\nstring tipo = Console.In.ReadToEnd().Trim();\nIAnimal a = tipo switch {\n    \"perro\" => new Perro(),\n    \"gato\" => new Gato(),\n    _ => new Vaca(),\n};\nConsole.WriteLine($\"sonido={a.Sonido()}\");\n\ninterface IAnimal { string Sonido(); }\nclass Perro : IAnimal { public string Sonido() => \"guau\"; }\nclass Gato : IAnimal { public string Sonido() => \"miau\"; }\nclass Vaca : IAnimal { public string Sonido() => \"muu\"; }\n",
        "go": "package main\n\nimport (\n\t\"bufio\"\n\t\"fmt\"\n\t\"os\"\n\t\"strings\"\n)\n\ntype Animal interface {\n\tsonido() string\n}\n\ntype Perro struct{}\ntype Gato struct{}\ntype Vaca struct{}\n\nfunc (Perro) sonido() string { return \"guau\" }\nfunc (Gato) sonido() string  { return \"miau\" }\nfunc (Vaca) sonido() string  { return \"muu\" }\n\nfunc main() {\n\tline, _ := bufio.NewReader(os.Stdin).ReadString('\\n')\n\ttipo := strings.TrimSpace(line)\n\tvar a Animal\n\tswitch tipo {\n\tcase \"perro\":\n\t\ta = Perro{}\n\tcase \"gato\":\n\t\ta = Gato{}\n\tdefault:\n\t\ta = Vaca{}\n\t}\n\tfmt.Printf(\"sonido=%s\\n\", a.sonido())\n}\n",
        "rust": "use std::io::Read;\n\ntrait Animal {\n    fn sonido(&self) -> &'static str;\n}\n\nstruct Perro;\nstruct Gato;\nstruct Vaca;\n\nimpl Animal for Perro { fn sonido(&self) -> &'static str { \"guau\" } }\nimpl Animal for Gato { fn sonido(&self) -> &'static str { \"miau\" } }\nimpl Animal for Vaca { fn sonido(&self) -> &'static str { \"muu\" } }\n\nfn main() {\n    let mut s = String::new();\n    std::io::stdin().read_to_string(&mut s).unwrap();\n    let tipo = s.trim();\n    let a: Box<dyn Animal> = match tipo {\n        \"perro\" => Box::new(Perro),\n        \"gato\" => Box::new(Gato),\n        _ => Box::new(Vaca),\n    };\n    println!(\"sonido={}\", a.sonido());\n}\n",
        "c": "#include <stdio.h>\n#include <string.h>\n\nint main(void) {\n    char tipo[32];\n    if (scanf(\"%31s\", tipo) != 1) return 1;\n    const char *sonido;\n    if (strcmp(tipo, \"perro\") == 0) sonido = \"guau\";\n    else if (strcmp(tipo, \"gato\") == 0) sonido = \"miau\";\n    else sonido = \"muu\";\n    printf(\"sonido=%s\\n\", sonido);\n    return 0;\n}\n",
        "php": "<?php\ninterface Animal { public function sonido(): string; }\nclass Perro implements Animal { public function sonido(): string { return \"guau\"; } }\nclass Gato implements Animal { public function sonido(): string { return \"miau\"; } }\nclass Vaca implements Animal { public function sonido(): string { return \"muu\"; } }\n\n$tipo = trim(fgets(STDIN));\n$animales = [\"perro\" => new Perro(), \"gato\" => new Gato(), \"vaca\" => new Vaca()];\necho \"sonido=\" . $animales[$tipo]->sonido() . \"\\n\";\n",
        "sql": "-- SQL: sin despacho polimórfico; se usa CASE.\nWITH animales(tipo) AS (VALUES ('perro'))\nSELECT printf('sonido=%s', CASE tipo WHEN 'perro' THEN 'guau' WHEN 'gato' THEN 'miau' ELSE 'muu' END) AS resultado\nFROM animales;\n",
    },
}

S[112] = {
    "descripcion": "Calcular el área de una figura a través de una interfaz común con método area().",
    "objetivo": "Usar **interfaces / traits / clases abstractas**: un contrato que varios tipos implementan. Distintas figuras exponen `area()` y el programa las usa sin conocer el tipo concreto.",
    "resultados": ["Definir un contrato (interfaz) y varias implementaciones.", "Programar contra la interfaz, no la implementación.", "Distinguir interfaz de clase abstracta."],
    "temas": [("Interfaz/trait", "Un contrato sin implementación"), ("Implementar", "Cumplir el contrato"), ("Programar contra la interfaz", "Desacoplar del tipo concreto")],
    "definiciones": [("Interfaz", "conjunto de métodos que un tipo promete implementar. Clave: contrato sin código."), ("Trait", "el equivalente en Rust; puede llevar métodos por defecto. Clave: composición de comportamiento."), ("Clase abstracta", "clase incompleta que otras extienden. Clave: contrato + estado parcial.")],
    "situacion": "`Forma` define `area()`; cuadrado y rectángulo lo implementan. El código que dibuja o mide no necesita saber qué figura es: confía en el contrato.",
    "entrada": "una línea: `cuadrado <lado>` o `rectangulo <ancho> <alto>`",
    "salida": "`area=<área>`",
    "formula": "cada figura implementa area() a su manera",
    "algoritmo": "LEER figura ; f: Forma ; ESCRIBIR f.area()",
    "casos": [("cuadrado 5", "area=25"), ("rectangulo 3 4", "area=12"), ("cuadrado 6", "area=36")],
    "comparacion": [("Sintáctica", "`interface` (Java/C#/Go/TS/PHP), `trait` (Rust), duck typing (Python/JS)."), ("Semántica", "El contrato desacopla el uso del tipo concreto."), ("Paradigmática", "SQL usa CASE; no hay interfaces.")],
    "familia": "En Kotlin, interfaces con métodos por defecto. En C++, clases abstractas con métodos virtuales puros.",
    "errores": [("Depender de la implementación concreta", "acoplamiento rígido", "programar contra la interfaz"), ("Interfaz demasiado grande", "difícil de implementar", "preferir interfaces pequeñas y enfocadas")],
    "faq": [("¿Interfaz o clase abstracta?", "Interfaz para un contrato puro; abstracta si compartes estado/código parcial."), ("¿Go tiene interfaces?", "Sí, y se cumplen implícitamente (structural typing).")],
    "reto": "Añade la figura `triangulo` (area = base·altura/2) al contrato y resuélvelo en **Rust** con un trait.",
    "impls": {
        "python": "import sys\n\n\nclass Cuadrado:\n    def __init__(self, l):\n        self.l = l\n    def area(self):\n        return self.l * self.l\n\n\nclass Rectangulo:\n    def __init__(self, a, b):\n        self.a, self.b = a, b\n    def area(self):\n        return self.a * self.b\n\n\nt = sys.stdin.readline().split()\nf = Cuadrado(int(t[1])) if t[0] == \"cuadrado\" else Rectangulo(int(t[1]), int(t[2]))\nprint(f\"area={f.area()}\")\n",
        "javascript": "import { readFileSync } from \"node:fs\";\n\nclass Cuadrado { constructor(l) { this.l = l; } area() { return this.l * this.l; } }\nclass Rectangulo { constructor(a, b) { this.a = a; this.b = b; } area() { return this.a * this.b; } }\n\nconst t = readFileSync(0, \"utf8\").trim().split(/\\s+/);\nconst f = t[0] === \"cuadrado\" ? new Cuadrado(Number(t[1])) : new Rectangulo(Number(t[1]), Number(t[2]));\nconsole.log(`area=${f.area()}`);\n",
        "typescript": "import { readFileSync } from \"node:fs\";\n\ninterface Forma { area(): number; }\nclass Cuadrado implements Forma { constructor(private l: number) {} area() { return this.l * this.l; } }\nclass Rectangulo implements Forma { constructor(private a: number, private b: number) {} area() { return this.a * this.b; } }\n\nconst t: string[] = readFileSync(0, \"utf8\").trim().split(/\\s+/);\nconst f: Forma = t[0] === \"cuadrado\" ? new Cuadrado(Number(t[1])) : new Rectangulo(Number(t[1]), Number(t[2]));\nconsole.log(`area=${f.area()}`);\n",
        "java": "import java.io.BufferedReader;\nimport java.io.IOException;\nimport java.io.InputStreamReader;\n\npublic class Main {\n    interface Forma { long area(); }\n    static class Cuadrado implements Forma {\n        long l; Cuadrado(long l) { this.l = l; }\n        public long area() { return l * l; }\n    }\n    static class Rectangulo implements Forma {\n        long a, b; Rectangulo(long a, long b) { this.a = a; this.b = b; }\n        public long area() { return a * b; }\n    }\n\n    public static void main(String[] args) throws IOException {\n        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));\n        String[] t = br.readLine().trim().split(\"\\\\s+\");\n        Forma f = t[0].equals(\"cuadrado\")\n                ? new Cuadrado(Long.parseLong(t[1]))\n                : new Rectangulo(Long.parseLong(t[1]), Long.parseLong(t[2]));\n        System.out.println(\"area=\" + f.area());\n    }\n}\n",
        "csharp": "using System;\n\nstring[] t = Console.In.ReadToEnd()\n    .Split(new[] { ' ', '\\t', '\\n', '\\r' }, StringSplitOptions.RemoveEmptyEntries);\nIForma f = t[0] == \"cuadrado\"\n    ? new Cuadrado(long.Parse(t[1]))\n    : new Rectangulo(long.Parse(t[1]), long.Parse(t[2]));\nConsole.WriteLine($\"area={f.Area()}\");\n\ninterface IForma { long Area(); }\nclass Cuadrado : IForma { long l; public Cuadrado(long l) { this.l = l; } public long Area() => l * l; }\nclass Rectangulo : IForma { long a, b; public Rectangulo(long a, long b) { this.a = a; this.b = b; } public long Area() => a * b; }\n",
        "go": "package main\n\nimport (\n\t\"bufio\"\n\t\"fmt\"\n\t\"os\"\n\t\"strconv\"\n\t\"strings\"\n)\n\ntype Forma interface {\n\tarea() int64\n}\n\ntype Cuadrado struct{ l int64 }\ntype Rectangulo struct{ a, b int64 }\n\nfunc (c Cuadrado) area() int64   { return c.l * c.l }\nfunc (r Rectangulo) area() int64 { return r.a * r.b }\n\nfunc main() {\n\tline, _ := bufio.NewReader(os.Stdin).ReadString('\\n')\n\tt := strings.Fields(line)\n\tvar f Forma\n\tif t[0] == \"cuadrado\" {\n\t\tl, _ := strconv.ParseInt(t[1], 10, 64)\n\t\tf = Cuadrado{l}\n\t} else {\n\t\ta, _ := strconv.ParseInt(t[1], 10, 64)\n\t\tb, _ := strconv.ParseInt(t[2], 10, 64)\n\t\tf = Rectangulo{a, b}\n\t}\n\tfmt.Printf(\"area=%d\\n\", f.area())\n}\n",
        "rust": "use std::io::Read;\n\ntrait Forma {\n    fn area(&self) -> i64;\n}\n\nstruct Cuadrado(i64);\nstruct Rectangulo(i64, i64);\n\nimpl Forma for Cuadrado { fn area(&self) -> i64 { self.0 * self.0 } }\nimpl Forma for Rectangulo { fn area(&self) -> i64 { self.0 * self.1 } }\n\nfn main() {\n    let mut s = String::new();\n    std::io::stdin().read_to_string(&mut s).unwrap();\n    let t: Vec<&str> = s.split_whitespace().collect();\n    let f: Box<dyn Forma> = if t[0] == \"cuadrado\" {\n        Box::new(Cuadrado(t[1].parse().unwrap()))\n    } else {\n        Box::new(Rectangulo(t[1].parse().unwrap(), t[2].parse().unwrap()))\n    };\n    println!(\"area={}\", f.area());\n}\n",
        "c": "#include <stdio.h>\n#include <string.h>\n\nint main(void) {\n    char tipo[32];\n    if (scanf(\"%31s\", tipo) != 1) return 1;\n    long area;\n    if (strcmp(tipo, \"cuadrado\") == 0) {\n        long l; if (scanf(\"%ld\", &l) != 1) return 1; area = l * l;\n    } else {\n        long a, b; if (scanf(\"%ld %ld\", &a, &b) != 2) return 1; area = a * b;\n    }\n    printf(\"area=%ld\\n\", area);\n    return 0;\n}\n",
        "php": "<?php\ninterface Forma { public function area(): int; }\nclass Cuadrado implements Forma {\n    public function __construct(private int $l) {}\n    public function area(): int { return $this->l * $this->l; }\n}\nclass Rectangulo implements Forma {\n    public function __construct(private int $a, private int $b) {}\n    public function area(): int { return $this->a * $this->b; }\n}\n\n$t = preg_split('/\\s+/', trim(fgets(STDIN)));\n$f = $t[0] === \"cuadrado\" ? new Cuadrado((int) $t[1]) : new Rectangulo((int) $t[1], (int) $t[2]);\necho \"area=\" . $f->area() . \"\\n\";\n",
        "sql": "-- SQL: sin interfaces; se usa CASE.\nWITH formas(tipo, a, b) AS (VALUES ('cuadrado', 5, 0))\nSELECT printf('area=%d', CASE WHEN tipo = 'cuadrado' THEN a * a ELSE a * b END) AS resultado FROM formas;\n",
    },
}

S[113] = {
    "descripcion": "Crear un objeto con un método doble() y usarlo, ilustrando el modelo de prototipos de JavaScript.",
    "objetivo": "Conocer la **OO basada en prototipos** de JavaScript: los objetos heredan directamente de otros objetos, no de clases. Aquí un objeto con un método `doble` calcula sobre su valor.",
    "resultados": ["Crear un objeto con estado y método.", "Explicar la herencia por prototipos.", "Contrastar prototipos con clases."],
    "temas": [("Prototipos", "Objetos que heredan de objetos"), ("Método en objeto", "Comportamiento ligado al valor"), ("Clases vs. prototipos", "Dos modelos de OO")],
    "definiciones": [("Prototipo", "objeto del que otro hereda propiedades y métodos. Clave: cadena de prototipos en JS."), ("Objeto literal", "objeto creado directamente con sus campos y métodos. Clave: `{ v: n, doble() {...} }`."), ("this", "referencia al objeto sobre el que se llama el método. Clave: accede a su estado.")],
    "situacion": "JavaScript no tenía clases originalmente: los objetos heredaban de otros objetos (prototipos). Aunque hoy tiene `class`, por debajo sigue siendo prototipos.",
    "entrada": "un entero `n`",
    "salida": "`resultado=<2n>`",
    "formula": "objeto.doble() = valor·2",
    "algoritmo": "obj <- { valor: n, doble() { DEVOLVER valor*2 } } ; ESCRIBIR obj.doble()",
    "casos": [("5", "resultado=10"), ("0", "resultado=0"), ("7", "resultado=14")],
    "comparacion": [("Sintáctica", "Objeto literal con método (JS) vs. clase (otros)."), ("Semántica", "JS hereda por prototipos; los demás por clases."), ("Paradigmática", "SQL no tiene objetos.")],
    "familia": "Self y Lua también usan prototipos. En los demás lenguajes del núcleo se modela con una clase o struct.",
    "errores": [("Perder el `this` en JS", "el método pierde su contexto", "cuidar cómo se invoca el método"), ("Creer que JS no es OO", "lo es, por prototipos", "entender el modelo de prototipos")],
    "faq": [("¿Prototipos o clases en JS?", "Las clases de JS son azúcar sobre prototipos; por debajo es lo mismo."), ("¿Qué lenguajes usan prototipos?", "JavaScript, Self, Lua; la mayoría usa clases.")],
    "reto": "Añade un método `triple` al mismo objeto y resuélvelo en **JavaScript**.",
    "impls": {
        "python": "import sys\n\nn = int(sys.stdin.readline())\nobj = {\"valor\": n}\ndef doble(o):\n    return o[\"valor\"] * 2\nprint(f\"resultado={doble(obj)}\")\n",
        "javascript": "import { readFileSync } from \"node:fs\";\n\nconst n = parseInt(readFileSync(0, \"utf8\").trim(), 10);\n// Objeto literal con método (modelo de prototipos).\nconst obj = {\n  valor: n,\n  doble() {\n    return this.valor * 2;\n  },\n};\nconsole.log(`resultado=${obj.doble()}`);\n",
        "typescript": "import { readFileSync } from \"node:fs\";\n\nconst n: number = parseInt(readFileSync(0, \"utf8\").trim(), 10);\nconst obj = {\n  valor: n,\n  doble(): number {\n    return this.valor * 2;\n  },\n};\nconsole.log(`resultado=${obj.doble()}`);\n",
        "java": "import java.io.BufferedReader;\nimport java.io.IOException;\nimport java.io.InputStreamReader;\n\npublic class Main {\n    static class Obj {\n        int valor;\n        Obj(int v) { valor = v; }\n        int doble() { return valor * 2; }\n    }\n\n    public static void main(String[] args) throws IOException {\n        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));\n        int n = Integer.parseInt(br.readLine().trim());\n        System.out.println(\"resultado=\" + new Obj(n).doble());\n    }\n}\n",
        "csharp": "using System;\n\nint n = int.Parse(Console.In.ReadToEnd().Trim());\nvar obj = new Obj(n);\nConsole.WriteLine($\"resultado={obj.Doble()}\");\n\nclass Obj {\n    int valor;\n    public Obj(int v) { valor = v; }\n    public int Doble() => valor * 2;\n}\n",
        "go": "package main\n\nimport (\n\t\"bufio\"\n\t\"fmt\"\n\t\"os\"\n\t\"strconv\"\n\t\"strings\"\n)\n\ntype Obj struct{ valor int }\n\nfunc (o Obj) doble() int { return o.valor * 2 }\n\nfunc main() {\n\tline, _ := bufio.NewReader(os.Stdin).ReadString('\\n')\n\tn, _ := strconv.Atoi(strings.TrimSpace(line))\n\to := Obj{valor: n}\n\tfmt.Printf(\"resultado=%d\\n\", o.doble())\n}\n",
        "rust": "use std::io::Read;\n\nstruct Obj {\n    valor: i64,\n}\n\nimpl Obj {\n    fn doble(&self) -> i64 {\n        self.valor * 2\n    }\n}\n\nfn main() {\n    let mut s = String::new();\n    std::io::stdin().read_to_string(&mut s).unwrap();\n    let n: i64 = s.trim().parse().unwrap();\n    let o = Obj { valor: n };\n    println!(\"resultado={}\", o.doble());\n}\n",
        "c": "#include <stdio.h>\n\nstruct Obj {\n    long valor;\n};\n\nlong doble(struct Obj *o) {\n    return o->valor * 2;\n}\n\nint main(void) {\n    long n;\n    if (scanf(\"%ld\", &n) != 1) return 1;\n    struct Obj o = {n};\n    printf(\"resultado=%ld\\n\", doble(&o));\n    return 0;\n}\n",
        "php": "<?php\n$n = (int) trim(fgets(STDIN));\n$obj = new class($n) {\n    public function __construct(public int $valor) {}\n    public function doble(): int { return $this->valor * 2; }\n};\necho \"resultado=\" . $obj->doble() . \"\\n\";\n",
        "sql": "-- SQL no tiene objetos; el cálculo va en la consulta.\nWITH nums(n) AS (VALUES (5), (0), (7))\nSELECT printf('resultado=%d', n * 2) AS resultado FROM nums;\n",
    },
}

S[114] = {
    "descripcion": "Duplicar cada elemento de una lista sin mutar la original (estilo funcional).",
    "objetivo": "Practicar el paradigma **funcional (I)**: inmutabilidad y funciones puras. Transformar una lista con `map` produce una lista nueva sin alterar la original ni usar estado mutable.",
    "resultados": ["Transformar una colección sin mutarla.", "Reconocer la inmutabilidad.", "Usar map en lugar de un bucle con estado."],
    "temas": [("Inmutabilidad", "No modificar, crear nuevo"), ("map", "Transformar cada elemento"), ("Sin estado mutable", "Sin acumuladores")],
    "definiciones": [("Funcional", "paradigma basado en funciones puras e inmutabilidad. Clave: sin efectos ni estado mutable."), ("Inmutabilidad", "los datos no cambian; las transformaciones crean nuevos. Clave: más seguro."), ("map", "aplica una función a cada elemento y devuelve una colección nueva. Clave: no muta.")],
    "situacion": "En vez de recorrer y mutar, el estilo funcional describe la transformación: 'la lista de los dobles'. La original queda intacta, lo que evita errores por estado compartido.",
    "entrada": "una línea con enteros separados por espacio",
    "salida": "`doblados=<cada x·2 unidos por ->`",
    "formula": "doblados = map(x → 2x, lista)",
    "algoritmo": "doblados <- MAP(x -> 2x, lista) ; ESCRIBIR unidos por -",
    "casos": [("1 2 3", "doblados=2-4-6"), ("5", "doblados=10"), ("2 4", "doblados=4-8")],
    "comparacion": [("Sintáctica", "`map` (Python/JS/Rust), streams (Java), LINQ Select (C#)."), ("Semántica", "No muta la lista original; devuelve otra."), ("Paradigmática", "SQL transforma en el SELECT, sin mutar.")],
    "familia": "En Haskell `map (*2) xs` es el ejemplo puro. Casi todos ofrecen map.",
    "errores": [("Mutar dentro del map", "efecto secundario", "mantener la transformación pura"), ("Confundir map con for-each", "map devuelve; for-each no", "usar map cuando quieres el resultado")],
    "faq": [("¿Map es más lento que un bucle?", "Generalmente comparable; y evita errores de estado."), ("¿Inmutabilidad no gasta memoria?", "Crea nuevos datos, pero permite compartir y razonar mejor.")],
    "reto": "Encadena map (doblar) y filter (mayores que 5); resuélvelo en **JavaScript**.",
    "impls": {
        "python": "import sys\n\nnums = [int(x) for x in sys.stdin.read().split()]\ndoblados = list(map(lambda x: x * 2, nums))\nprint(\"doblados=\" + \"-\".join(str(x) for x in doblados))\n",
        "javascript": "import { readFileSync } from \"node:fs\";\n\nconst nums = readFileSync(0, \"utf8\").trim().split(/\\s+/).map(Number);\nconst doblados = nums.map((x) => x * 2);\nconsole.log(`doblados=${doblados.join(\"-\")}`);\n",
        "typescript": "import { readFileSync } from \"node:fs\";\n\nconst nums: number[] = readFileSync(0, \"utf8\").trim().split(/\\s+/).map(Number);\nconst doblados: number[] = nums.map((x) => x * 2);\nconsole.log(`doblados=${doblados.join(\"-\")}`);\n",
        "java": "import java.io.BufferedReader;\nimport java.io.IOException;\nimport java.io.InputStreamReader;\nimport java.util.Arrays;\nimport java.util.stream.Collectors;\n\npublic class Main {\n    public static void main(String[] args) throws IOException {\n        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));\n        String[] p = br.readLine().trim().split(\"\\\\s+\");\n        String r = Arrays.stream(p).map(Integer::parseInt).map(x -> x * 2)\n                .map(String::valueOf).collect(Collectors.joining(\"-\"));\n        System.out.println(\"doblados=\" + r);\n    }\n}\n",
        "csharp": "using System;\nusing System.Linq;\n\nstring[] p = Console.In.ReadToEnd()\n    .Split(new[] { ' ', '\\t', '\\n', '\\r' }, StringSplitOptions.RemoveEmptyEntries);\nvar doblados = p.Select(int.Parse).Select(x => x * 2);\nConsole.WriteLine($\"doblados={string.Join(\"-\", doblados)}\");\n",
        "go": "package main\n\nimport (\n\t\"bufio\"\n\t\"fmt\"\n\t\"os\"\n\t\"strconv\"\n\t\"strings\"\n)\n\nfunc main() {\n\tline, _ := bufio.NewReader(os.Stdin).ReadString('\\n')\n\tvar doblados []string\n\tfor _, s := range strings.Fields(line) {\n\t\tn, _ := strconv.Atoi(s)\n\t\tdoblados = append(doblados, strconv.Itoa(n*2))\n\t}\n\tfmt.Printf(\"doblados=%s\\n\", strings.Join(doblados, \"-\"))\n}\n",
        "rust": "use std::io::Read;\n\nfn main() {\n    let mut s = String::new();\n    std::io::stdin().read_to_string(&mut s).unwrap();\n    let doblados: Vec<String> = s\n        .split_whitespace()\n        .map(|x| (x.parse::<i64>().unwrap() * 2).to_string())\n        .collect();\n    println!(\"doblados={}\", doblados.join(\"-\"));\n}\n",
        "c": "#include <stdio.h>\n\nint main(void) {\n    long x;\n    int primero = 1;\n    printf(\"doblados=\");\n    while (scanf(\"%ld\", &x) == 1) {\n        if (!primero) printf(\"-\");\n        printf(\"%ld\", x * 2);\n        primero = 0;\n    }\n    printf(\"\\n\");\n    return 0;\n}\n",
        "php": "<?php\n$nums = array_map('intval', preg_split('/\\s+/', trim(fgets(STDIN))));\n$doblados = array_map(fn($x) => $x * 2, $nums);\necho \"doblados=\" . implode(\"-\", $doblados) . \"\\n\";\n",
        "sql": "-- SQL: la transformación va en el SELECT, sin mutar.\nWITH nums(x) AS (VALUES (1), (2), (3))\nSELECT 'doblados=' || group_concat(x * 2, '-') AS resultado FROM nums;\n",
    },
}

S[115] = {
    "descripcion": "Componer dos funciones (doblar y luego sumar uno) y aplicarlas a un número.",
    "objetivo": "Practicar el paradigma **funcional (II)**: composición de funciones. Combinar funciones pequeñas (`doblar`, `incrementar`) en una mayor, aplicando primero una y luego la otra.",
    "resultados": ["Componer dos funciones.", "Aplicar la composición a un valor.", "Reconocer la aplicación parcial/currying."],
    "temas": [("Composición", "f(g(x)): encadenar funciones"), ("Funciones pequeñas", "Construir a partir de piezas"), ("Currying", "Funciones que devuelven funciones")],
    "definiciones": [("Composición de funciones", "combinar funciones: `(f ∘ g)(x) = f(g(x))`. Clave: construir con piezas."), ("Currying", "transformar una función de varios argumentos en una cadena de funciones de uno. Clave: aplicación parcial."), ("Aplicación parcial", "fijar algunos argumentos y obtener una función nueva. Clave: reutilización.")],
    "situacion": "En vez de escribir `x*2+1` a mano, se componen `doblar` e `incrementar`. Las funciones pequeñas y componibles son el corazón del estilo funcional.",
    "entrada": "un entero `n`",
    "salida": "`resultado=<2n+1>` (doblar y luego incrementar)",
    "formula": "resultado = incrementar(doblar(n)) = 2n + 1",
    "algoritmo": "doblar(x)=2x ; inc(x)=x+1 ; compuesta = inc ∘ doblar ; ESCRIBIR compuesta(n)",
    "casos": [("5", "resultado=11"), ("0", "resultado=1"), ("3", "resultado=7")],
    "comparacion": [("Sintáctica", "Composición explícita `inc(doblar(n))` o con operador de composición."), ("Semántica", "El orden importa: doblar primero, luego incrementar."), ("Paradigmática", "SQL anida funciones/expresiones.")],
    "familia": "En Haskell `(inc . doblar) n` con el operador `.`. En muchos lenguajes se anidan las llamadas.",
    "errores": [("Invertir el orden de composición", "resultado distinto", "aplicar en el orden correcto"), ("Componer funciones incompatibles", "tipos que no encajan", "asegurar que la salida de una es la entrada de la otra")],
    "faq": [("¿Composición o anidar llamadas?", "Anidar es composición explícita; algunos lenguajes tienen un operador dedicado."), ("¿Currying para qué sirve?", "Fijar argumentos y crear funciones especializadas reutilizables.")],
    "reto": "Compón tres funciones (doblar, incrementar, cuadrado) y resuélvelo en **Python**.",
    "impls": {
        "python": "import sys\n\n\ndef doblar(x):\n    return x * 2\n\n\ndef incrementar(x):\n    return x + 1\n\n\nn = int(sys.stdin.readline())\nprint(f\"resultado={incrementar(doblar(n))}\")\n",
        "javascript": "import { readFileSync } from \"node:fs\";\n\nconst doblar = (x) => x * 2;\nconst incrementar = (x) => x + 1;\nconst compuesta = (x) => incrementar(doblar(x));\n\nconst n = parseInt(readFileSync(0, \"utf8\").trim(), 10);\nconsole.log(`resultado=${compuesta(n)}`);\n",
        "typescript": "import { readFileSync } from \"node:fs\";\n\nconst doblar = (x: number): number => x * 2;\nconst incrementar = (x: number): number => x + 1;\nconst compuesta = (x: number): number => incrementar(doblar(x));\n\nconst n: number = parseInt(readFileSync(0, \"utf8\").trim(), 10);\nconsole.log(`resultado=${compuesta(n)}`);\n",
        "java": "import java.io.BufferedReader;\nimport java.io.IOException;\nimport java.io.InputStreamReader;\nimport java.util.function.IntUnaryOperator;\n\npublic class Main {\n    public static void main(String[] args) throws IOException {\n        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));\n        int n = Integer.parseInt(br.readLine().trim());\n        IntUnaryOperator doblar = x -> x * 2;\n        IntUnaryOperator incrementar = x -> x + 1;\n        IntUnaryOperator compuesta = doblar.andThen(incrementar);\n        System.out.println(\"resultado=\" + compuesta.applyAsInt(n));\n    }\n}\n",
        "csharp": "using System;\n\nint n = int.Parse(Console.In.ReadToEnd().Trim());\nFunc<int, int> doblar = x => x * 2;\nFunc<int, int> incrementar = x => x + 1;\nFunc<int, int> compuesta = x => incrementar(doblar(x));\nConsole.WriteLine($\"resultado={compuesta(n)}\");\n",
        "go": "package main\n\nimport (\n\t\"bufio\"\n\t\"fmt\"\n\t\"os\"\n\t\"strconv\"\n\t\"strings\"\n)\n\nfunc doblar(x int) int      { return x * 2 }\nfunc incrementar(x int) int { return x + 1 }\n\nfunc main() {\n\tline, _ := bufio.NewReader(os.Stdin).ReadString('\\n')\n\tn, _ := strconv.Atoi(strings.TrimSpace(line))\n\tfmt.Printf(\"resultado=%d\\n\", incrementar(doblar(n)))\n}\n",
        "rust": "use std::io::Read;\n\nfn doblar(x: i64) -> i64 {\n    x * 2\n}\n\nfn incrementar(x: i64) -> i64 {\n    x + 1\n}\n\nfn main() {\n    let mut s = String::new();\n    std::io::stdin().read_to_string(&mut s).unwrap();\n    let n: i64 = s.trim().parse().unwrap();\n    println!(\"resultado={}\", incrementar(doblar(n)));\n}\n",
        "c": "#include <stdio.h>\n\nlong doblar(long x) { return x * 2; }\nlong incrementar(long x) { return x + 1; }\n\nint main(void) {\n    long n;\n    if (scanf(\"%ld\", &n) != 1) return 1;\n    printf(\"resultado=%ld\\n\", incrementar(doblar(n)));\n    return 0;\n}\n",
        "php": "<?php\n$doblar = fn($x) => $x * 2;\n$incrementar = fn($x) => $x + 1;\n$compuesta = fn($x) => $incrementar($doblar($x));\n\n$n = (int) trim(fgets(STDIN));\necho \"resultado=\" . $compuesta($n) . \"\\n\";\n",
        "sql": "-- SQL: se anidan las expresiones/funciones.\nWITH nums(n) AS (VALUES (5), (0), (3))\nSELECT printf('resultado=%d', (n * 2) + 1) AS resultado FROM nums;\n",
    },
}

S[116] = {
    "descripcion": "Aplicar una operación a un valor solo si existe (positivo); si no, indicar ausencia. Modelo Option/Maybe.",
    "objetivo": "Practicar el paradigma **funcional (III)**: functores y mónadas en su forma práctica. `Option`/`Maybe` envuelve 'hay valor' o 'no hay', y `map` aplica una función solo si hay valor, sin comprobaciones dispersas.",
    "resultados": ["Envolver un valor opcional.", "Aplicar map sobre Option (functor).", "Explicar la ventaja frente a null."],
    "temas": [("Option/Maybe", "Contenedor de 'quizá hay valor'"), ("map sobre contenedor", "Aplicar sin desenvolver"), ("Functor", "Algo sobre lo que se puede mapear")],
    "definiciones": [("Functor", "contenedor sobre el que se puede aplicar `map` (Option, listas). Clave: transformar el contenido sin sacarlo."), ("Option/Maybe", "envuelve un valor presente (Some) o ausente (None). Clave: ausencia explícita y segura."), ("map sobre Option", "aplica la función si hay valor; si no, propaga la ausencia. Clave: sin ifs dispersos.")],
    "situacion": "En vez de `if (x != null) usar(x)` por todas partes, `option.map(usar)` aplica la función solo si hay valor y propaga la ausencia. Menos ruido, menos errores de null.",
    "entrada": "un entero `n`",
    "salida": "`resultado=<2n>` si n>0 (hay valor), o `resultado=nada` si no",
    "formula": "Option(n si n>0).map(x → 2x)",
    "algoritmo": "opcion <- Some(n) SI n>0 SINO None ; ESCRIBIR opcion.map(x->2x) o 'nada'",
    "casos": [("5", "resultado=10"), ("0", "resultado=nada"), ("-3", "resultado=nada")],
    "comparacion": [("Sintáctica", "`Option`/`map` (Rust), `Optional` (Java), if/else (otros)."), ("Semántica", "El functor evita comprobar la ausencia en cada paso."), ("Paradigmática", "SQL propaga NULL automáticamente por las operaciones.")],
    "familia": "En Haskell `fmap (*2) (Just n)`. En Kotlin, `?.let { it * 2 }` sobre un tipo nullable.",
    "errores": [("Desenvolver sin comprobar", "usar un valor ausente", "usar map/flatMap en vez de extraer a la fuerza"), ("Confundir functor con mónada", "map vs. flatMap", "map transforma; flatMap encadena operaciones que devuelven Option")],
    "faq": [("¿Functor o mónada?", "Functor solo mapea; la mónada además encadena (flatMap). Aquí basta map."), ("¿Por qué mejor que null?", "El tipo obliga a considerar la ausencia; el null se cuela silenciosamente.")],
    "reto": "Encadena dos operaciones que pueden fallar con flatMap y resuélvelo en **Rust** con `Option`.",
    "impls": {
        "python": "import sys\n\nn = int(sys.stdin.readline())\nopcion = n if n > 0 else None\nif opcion is not None:\n    print(f\"resultado={opcion * 2}\")\nelse:\n    print(\"resultado=nada\")\n",
        "javascript": "import { readFileSync } from \"node:fs\";\n\nconst n = parseInt(readFileSync(0, \"utf8\").trim(), 10);\nconst opcion = n > 0 ? n : null;\nconsole.log(opcion !== null ? `resultado=${opcion * 2}` : \"resultado=nada\");\n",
        "typescript": "import { readFileSync } from \"node:fs\";\n\nconst n: number = parseInt(readFileSync(0, \"utf8\").trim(), 10);\nconst opcion: number | null = n > 0 ? n : null;\nconsole.log(opcion !== null ? `resultado=${opcion * 2}` : \"resultado=nada\");\n",
        "java": "import java.io.BufferedReader;\nimport java.io.IOException;\nimport java.io.InputStreamReader;\nimport java.util.Optional;\n\npublic class Main {\n    public static void main(String[] args) throws IOException {\n        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));\n        int n = Integer.parseInt(br.readLine().trim());\n        Optional<Integer> opcion = n > 0 ? Optional.of(n) : Optional.empty();\n        Optional<Integer> r = opcion.map(x -> x * 2);\n        System.out.println(r.map(x -> \"resultado=\" + x).orElse(\"resultado=nada\"));\n    }\n}\n",
        "csharp": "using System;\n\nint n = int.Parse(Console.In.ReadToEnd().Trim());\nint? opcion = n > 0 ? n : (int?) null;\nint? r = opcion.HasValue ? opcion.Value * 2 : (int?) null;\nConsole.WriteLine(r.HasValue ? $\"resultado={r.Value}\" : \"resultado=nada\");\n",
        "go": "package main\n\nimport (\n\t\"bufio\"\n\t\"fmt\"\n\t\"os\"\n\t\"strconv\"\n\t\"strings\"\n)\n\nfunc main() {\n\tline, _ := bufio.NewReader(os.Stdin).ReadString('\\n')\n\tn, _ := strconv.Atoi(strings.TrimSpace(line))\n\tif n > 0 {\n\t\tfmt.Printf(\"resultado=%d\\n\", n*2)\n\t} else {\n\t\tfmt.Println(\"resultado=nada\")\n\t}\n}\n",
        "rust": "use std::io::Read;\n\nfn main() {\n    let mut s = String::new();\n    std::io::stdin().read_to_string(&mut s).unwrap();\n    let n: i64 = s.trim().parse().unwrap();\n    let opcion: Option<i64> = if n > 0 { Some(n) } else { None };\n    match opcion.map(|x| x * 2) {\n        Some(r) => println!(\"resultado={r}\"),\n        None => println!(\"resultado=nada\"),\n    }\n}\n",
        "c": "#include <stdio.h>\n\nint main(void) {\n    long n;\n    if (scanf(\"%ld\", &n) != 1) return 1;\n    if (n > 0) {\n        printf(\"resultado=%ld\\n\", n * 2);\n    } else {\n        printf(\"resultado=nada\\n\");\n    }\n    return 0;\n}\n",
        "php": "<?php\n$n = (int) trim(fgets(STDIN));\n$opcion = $n > 0 ? $n : null;\necho $opcion !== null ? \"resultado=\" . ($opcion * 2) . \"\\n\" : \"resultado=nada\\n\";\n",
        "sql": "-- SQL propaga NULL por las operaciones automáticamente.\nWITH nums(n) AS (VALUES (5), (0), (-3))\nSELECT CASE WHEN n > 0 THEN printf('resultado=%d', n * 2) ELSE 'resultado=nada' END AS resultado\nFROM nums;\n",
    },
}

S[117] = {
    "descripcion": "Sumar solo los números pares de una lista, en estilo declarativo.",
    "objetivo": "Practicar el paradigma **declarativo**: describir *qué* resultado se quiere, no *cómo* obtenerlo. Sumar los pares se expresa como 'la suma de los que son pares', dejando el cómo al lenguaje.",
    "resultados": ["Expresar un cálculo de forma declarativa.", "Combinar filtro y agregación.", "Contrastar con el estilo imperativo."],
    "temas": [("Declarativo", "Describir el resultado"), ("Filtro + agregación", "Seleccionar y combinar"), ("SQL como declarativo", "WHERE + SUM")],
    "definiciones": [("Declarativo", "paradigma que describe el resultado deseado, no los pasos. Clave: el motor decide el cómo."), ("Filtro", "seleccionar los elementos que cumplen una condición. Clave: `WHERE`, `filter`."), ("Agregación", "combinar varios valores en uno (suma). Clave: `SUM`, `reduce`.")],
    "situacion": "'La suma de los pedidos pagados', 'el total de las ventas del mes': el estilo declarativo describe el resultado. SQL es su máximo exponente: `SELECT SUM(x) WHERE ...`.",
    "entrada": "una línea con enteros separados por espacio",
    "salida": "`suma_pares=<suma de los pares>`",
    "formula": "suma de los x tales que x es par",
    "algoritmo": "suma_pares <- SUMA(FILTRAR(par, lista))",
    "casos": [("1 2 3 4", "suma_pares=6"), ("2 4 6", "suma_pares=12"), ("1 3 5", "suma_pares=0")],
    "comparacion": [("Sintáctica", "`sum(x for x in l if x%2==0)` (Python), `filter+reduce` (JS), `WHERE+SUM` (SQL)."), ("Semántica", "Se describe el resultado; el cómo queda implícito."), ("Paradigmática", "El imperativo recorrería y acumularía a mano.")],
    "familia": "En Haskell `sum (filter even xs)`. SQL es el declarativo por excelencia.",
    "errores": [("Mezclar el cómo con el qué", "perder la claridad declarativa", "describir el resultado, dejar el cómo al lenguaje"), ("Olvidar el caso sin pares", "esperar error en vez de 0", "la suma vacía es 0")],
    "faq": [("¿Declarativo siempre es mejor?", "Es más legible para transformaciones de datos; el imperativo da más control fino."), ("¿SQL es declarativo?", "Sí, el ejemplo canónico: describes el resultado, no el algoritmo.")],
    "reto": "Cuenta cuántos pares hay además de sumarlos y resuélvelo en **SQL**.",
    "impls": {
        "python": "import sys\n\nnums = [int(x) for x in sys.stdin.read().split()]\nprint(f\"suma_pares={sum(x for x in nums if x % 2 == 0)}\")\n",
        "javascript": "import { readFileSync } from \"node:fs\";\n\nconst nums = readFileSync(0, \"utf8\").trim().split(/\\s+/).map(Number);\nconst suma = nums.filter((x) => x % 2 === 0).reduce((a, b) => a + b, 0);\nconsole.log(`suma_pares=${suma}`);\n",
        "typescript": "import { readFileSync } from \"node:fs\";\n\nconst nums: number[] = readFileSync(0, \"utf8\").trim().split(/\\s+/).map(Number);\nconst suma = nums.filter((x) => x % 2 === 0).reduce((a, b) => a + b, 0);\nconsole.log(`suma_pares=${suma}`);\n",
        "java": "import java.io.BufferedReader;\nimport java.io.IOException;\nimport java.io.InputStreamReader;\nimport java.util.Arrays;\n\npublic class Main {\n    public static void main(String[] args) throws IOException {\n        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));\n        String[] p = br.readLine().trim().split(\"\\\\s+\");\n        long suma = Arrays.stream(p).mapToInt(Integer::parseInt).filter(x -> x % 2 == 0).sum();\n        System.out.println(\"suma_pares=\" + suma);\n    }\n}\n",
        "csharp": "using System;\nusing System.Linq;\n\nstring[] p = Console.In.ReadToEnd()\n    .Split(new[] { ' ', '\\t', '\\n', '\\r' }, StringSplitOptions.RemoveEmptyEntries);\nlong suma = p.Select(int.Parse).Where(x => x % 2 == 0).Sum(x => (long) x);\nConsole.WriteLine($\"suma_pares={suma}\");\n",
        "go": "package main\n\nimport (\n\t\"bufio\"\n\t\"fmt\"\n\t\"os\"\n\t\"strconv\"\n\t\"strings\"\n)\n\nfunc main() {\n\tline, _ := bufio.NewReader(os.Stdin).ReadString('\\n')\n\tsuma := 0\n\tfor _, s := range strings.Fields(line) {\n\t\tn, _ := strconv.Atoi(s)\n\t\tif n%2 == 0 {\n\t\t\tsuma += n\n\t\t}\n\t}\n\tfmt.Printf(\"suma_pares=%d\\n\", suma)\n}\n",
        "rust": "use std::io::Read;\n\nfn main() {\n    let mut s = String::new();\n    std::io::stdin().read_to_string(&mut s).unwrap();\n    let suma: i64 = s\n        .split_whitespace()\n        .map(|x| x.parse::<i64>().unwrap())\n        .filter(|x| x % 2 == 0)\n        .sum();\n    println!(\"suma_pares={suma}\");\n}\n",
        "c": "#include <stdio.h>\n\nint main(void) {\n    long suma = 0, x;\n    while (scanf(\"%ld\", &x) == 1) {\n        if (x % 2 == 0) suma += x;\n    }\n    printf(\"suma_pares=%ld\\n\", suma);\n    return 0;\n}\n",
        "php": "<?php\n$nums = array_map('intval', preg_split('/\\s+/', trim(fgets(STDIN))));\n$suma = array_sum(array_filter($nums, fn($x) => $x % 2 === 0));\necho \"suma_pares=$suma\\n\";\n",
        "sql": "-- SQL: WHERE + SUM, puro estilo declarativo.\nWITH nums(x) AS (VALUES (1), (2), (3), (4))\nSELECT printf('suma_pares=%d', COALESCE(sum(x), 0)) AS resultado FROM nums WHERE x % 2 = 0;\n",
    },
}

S[118] = {
    "descripcion": "Determinar si un número divide a otro, expresado como una regla lógica.",
    "objetivo": "Asomarse al paradigma **lógico** (Prolog): en vez de calcular paso a paso, se declaran hechos y reglas y se consulta si algo se cumple. Aquí la regla `es_divisor(a, b)` es verdadera si a divide a b.",
    "resultados": ["Expresar una relación como regla lógica.", "Consultar si la relación se cumple.", "Contrastar lógico con imperativo."],
    "temas": [("Programación lógica", "Hechos y reglas"), ("Regla", "Relación que se cumple o no"), ("Consulta", "Preguntar por la verdad de algo")],
    "definiciones": [("Lógico", "paradigma en el que se declaran hechos y reglas y se consultan (Prolog). Clave: el motor deduce."), ("Regla", "relación condicional entre términos. Clave: `es_divisor(A,B) :- B mod A =:= 0`."), ("Consulta", "pregunta al sistema sobre si algo se cumple. Clave: devuelve verdadero/falso o soluciones.")],
    "situacion": "En Prolog no dices cómo comprobar la divisibilidad: declaras la regla y preguntas `es_divisor(3, 12)`. El motor responde. Es el estilo de los sistemas expertos y el razonamiento.",
    "entrada": "una línea `a b` (dos enteros, a != 0)",
    "salida": "`divisor=<true|false>` (¿a divide a b?)",
    "formula": "divisor = (b mod a == 0)",
    "algoritmo": "REGLA es_divisor(a,b) SI b mod a == 0 ; CONSULTAR es_divisor(a,b)",
    "casos": [("3 12", "divisor=true"), ("5 12", "divisor=false"), ("4 12", "divisor=true")],
    "comparacion": [("Sintáctica", "En los del núcleo es un `if (b % a == 0)`; en Prolog, una regla."), ("Semántica", "El lógico deduce; los imperativos comprueban."), ("Paradigmática", "SQL (declarativo) es primo del lógico: describe condiciones.")],
    "familia": "En Prolog: `es_divisor(A, B) :- 0 is B mod A.` y la consulta `?- es_divisor(3, 12).`. Datalog es un subconjunto para datos.",
    "errores": [("Confundir lógico con imperativo", "querer controlar el cómo", "declarar la relación y consultar"), ("División por cero en la regla", "a = 0", "aquí a != 0")],
    "faq": [("¿Dónde se usa Prolog?", "IA simbólica, sistemas expertos, análisis de lenguaje, verificación."), ("¿SQL es lógico?", "Es declarativo, primo cercano; describe condiciones sobre datos.")],
    "reto": "Declara la regla `es_par(n)` y consúltala; resuélvelo conceptualmente en **Prolog** y en **Python**.",
    "impls": {
        "python": "import sys\n\na, b = map(int, sys.stdin.readline().split())\nes_divisor = b % a == 0\nprint(f\"divisor={'true' if es_divisor else 'false'}\")\n",
        "javascript": "import { readFileSync } from \"node:fs\";\n\nconst [a, b] = readFileSync(0, \"utf8\").trim().split(/\\s+/).map(Number);\nconsole.log(`divisor=${b % a === 0 ? \"true\" : \"false\"}`);\n",
        "typescript": "import { readFileSync } from \"node:fs\";\n\nconst [a, b]: number[] = readFileSync(0, \"utf8\").trim().split(/\\s+/).map(Number);\nconsole.log(`divisor=${b % a === 0 ? \"true\" : \"false\"}`);\n",
        "java": "import java.io.BufferedReader;\nimport java.io.IOException;\nimport java.io.InputStreamReader;\n\npublic class Main {\n    static boolean esDivisor(long a, long b) {\n        return b % a == 0;\n    }\n\n    public static void main(String[] args) throws IOException {\n        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));\n        String[] p = br.readLine().trim().split(\"\\\\s+\");\n        long a = Long.parseLong(p[0]);\n        long b = Long.parseLong(p[1]);\n        System.out.println(\"divisor=\" + (esDivisor(a, b) ? \"true\" : \"false\"));\n    }\n}\n",
        "csharp": "using System;\n\nstring[] p = Console.In.ReadToEnd()\n    .Split(new[] { ' ', '\\t', '\\n', '\\r' }, StringSplitOptions.RemoveEmptyEntries);\nlong a = long.Parse(p[0]);\nlong b = long.Parse(p[1]);\nConsole.WriteLine($\"divisor={(b % a == 0 ? \"true\" : \"false\")}\");\n",
        "go": "package main\n\nimport (\n\t\"bufio\"\n\t\"fmt\"\n\t\"os\"\n\t\"strconv\"\n\t\"strings\"\n)\n\nfunc main() {\n\tline, _ := bufio.NewReader(os.Stdin).ReadString('\\n')\n\tf := strings.Fields(line)\n\ta, _ := strconv.Atoi(f[0])\n\tb, _ := strconv.Atoi(f[1])\n\tres := \"false\"\n\tif b%a == 0 {\n\t\tres = \"true\"\n\t}\n\tfmt.Printf(\"divisor=%s\\n\", res)\n}\n",
        "rust": "use std::io::Read;\n\nfn main() {\n    let mut s = String::new();\n    std::io::stdin().read_to_string(&mut s).unwrap();\n    let v: Vec<i64> = s.split_whitespace().map(|x| x.parse().unwrap()).collect();\n    let res = if v[1] % v[0] == 0 { \"true\" } else { \"false\" };\n    println!(\"divisor={res}\");\n}\n",
        "c": "#include <stdio.h>\n\nint main(void) {\n    long a, b;\n    if (scanf(\"%ld %ld\", &a, &b) != 2) return 1;\n    printf(\"divisor=%s\\n\", b % a == 0 ? \"true\" : \"false\");\n    return 0;\n}\n",
        "php": "<?php\n[$a, $b] = preg_split('/\\s+/', trim(fgets(STDIN)));\necho \"divisor=\" . ((int) $b % (int) $a === 0 ? \"true\" : \"false\") . \"\\n\";\n",
        "sql": "-- SQL (declarativo, primo del lógico): la condición como CASE.\nWITH pares(a, b) AS (VALUES (3, 12), (5, 12), (4, 12))\nSELECT printf('divisor=%s', CASE WHEN b % a = 0 THEN 'true' ELSE 'false' END) AS resultado FROM pares;\n",
    },
}

S[119] = {
    "descripcion": "Emitir un evento por cada número de 1 a n y recolectar en un manejador (callback) el orden de llegada.",
    "objetivo": "Practicar el paradigma **orientado a eventos y callbacks**: en vez de un flujo lineal, se registran manejadores que reaccionan cuando ocurre un evento. Aquí un callback recolecta cada evento emitido.",
    "resultados": ["Registrar un callback.", "Emitir eventos que lo invocan.", "Reconocer la inversión de control."],
    "temas": [("Evento", "Algo que ocurre"), ("Callback/manejador", "Función que reacciona"), ("Inversión de control", "El sistema llama a tu código")],
    "definiciones": [("Evento", "suceso al que el programa reacciona (clic, mensaje, dato). Clave: dispara callbacks."), ("Callback", "función registrada para ejecutarse cuando ocurre el evento. Clave: no la llamas tú."), ("Inversión de control", "el sistema invoca tu código, no al revés. Clave: base de la GUI y del servidor.")],
    "situacion": "Interfaces, servidores, sensores: no siguen un guion lineal, reaccionan a eventos. Registras un callback ('cuando llegue X, haz Y') y el sistema lo invoca.",
    "entrada": "un entero `n` (número de eventos, n >= 1)",
    "salida": "`eventos=<1-2-...-n>` (orden en que llegaron)",
    "formula": "por cada i en 1..n, emitir evento i; el callback lo recolecta",
    "algoritmo": "registrar callback ; PARA i de 1 a n: emitir(i) ; ESCRIBIR recolectados",
    "casos": [("3", "eventos=1-2-3"), ("1", "eventos=1"), ("4", "eventos=1-2-3-4")],
    "comparacion": [("Sintáctica", "Callback como función pasada (Python/JS/Go), delegate (C#), interfaz (Java)."), ("Semántica", "El emisor invoca el callback; el flujo no es lineal."), ("Paradigmática", "SQL no tiene eventos; procesa datos.")],
    "familia": "En JS los EventEmitter y los `addEventListener` del navegador son puro estilo de eventos.",
    "errores": [("Callback con efectos secundarios ocultos", "estado difícil de seguir", "mantener el callback claro y enfocado"), ("Olvidar registrar el manejador", "el evento no hace nada", "registrar antes de emitir")],
    "faq": [("¿Callback o async/await?", "async/await suele leer mejor; ambos manejan lo asíncrono/eventos."), ("¿Qué es inversión de control?", "Que el framework/sistema llame a tu código cuando toca, no tú a él.")],
    "reto": "Filtra los eventos pares en el callback y resuélvelo en **JavaScript**.",
    "impls": {
        "python": "import sys\n\nrecolectados = []\n\n\ndef al_evento(i):\n    recolectados.append(i)\n\n\nn = int(sys.stdin.readline())\nfor i in range(1, n + 1):\n    al_evento(i)\nprint(\"eventos=\" + \"-\".join(str(x) for x in recolectados))\n",
        "javascript": "import { readFileSync } from \"node:fs\";\n\nconst recolectados = [];\nconst alEvento = (i) => recolectados.push(i);\n\nconst n = parseInt(readFileSync(0, \"utf8\").trim(), 10);\nfor (let i = 1; i <= n; i++) alEvento(i);\nconsole.log(`eventos=${recolectados.join(\"-\")}`);\n",
        "typescript": "import { readFileSync } from \"node:fs\";\n\nconst recolectados: number[] = [];\nconst alEvento = (i: number): void => {\n  recolectados.push(i);\n};\n\nconst n: number = parseInt(readFileSync(0, \"utf8\").trim(), 10);\nfor (let i = 1; i <= n; i++) alEvento(i);\nconsole.log(`eventos=${recolectados.join(\"-\")}`);\n",
        "java": "import java.io.BufferedReader;\nimport java.io.IOException;\nimport java.io.InputStreamReader;\nimport java.util.ArrayList;\nimport java.util.List;\nimport java.util.function.IntConsumer;\nimport java.util.stream.Collectors;\n\npublic class Main {\n    public static void main(String[] args) throws IOException {\n        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));\n        int n = Integer.parseInt(br.readLine().trim());\n        List<Integer> recolectados = new ArrayList<>();\n        IntConsumer alEvento = recolectados::add;\n        for (int i = 1; i <= n; i++) alEvento.accept(i);\n        System.out.println(\"eventos=\" + recolectados.stream().map(String::valueOf).collect(Collectors.joining(\"-\")));\n    }\n}\n",
        "csharp": "using System;\nusing System.Collections.Generic;\n\nint n = int.Parse(Console.In.ReadToEnd().Trim());\nvar recolectados = new List<int>();\nAction<int> alEvento = i => recolectados.Add(i);\nfor (int i = 1; i <= n; i++) alEvento(i);\nConsole.WriteLine($\"eventos={string.Join(\"-\", recolectados)}\");\n",
        "go": "package main\n\nimport (\n\t\"bufio\"\n\t\"fmt\"\n\t\"os\"\n\t\"strconv\"\n\t\"strings\"\n)\n\nfunc main() {\n\tline, _ := bufio.NewReader(os.Stdin).ReadString('\\n')\n\tn, _ := strconv.Atoi(strings.TrimSpace(line))\n\tvar recolectados []string\n\talEvento := func(i int) {\n\t\trecolectados = append(recolectados, strconv.Itoa(i))\n\t}\n\tfor i := 1; i <= n; i++ {\n\t\talEvento(i)\n\t}\n\tfmt.Printf(\"eventos=%s\\n\", strings.Join(recolectados, \"-\"))\n}\n",
        "rust": "use std::io::Read;\n\nfn al_evento(recolectados: &mut Vec<String>, i: i64) {\n    recolectados.push(i.to_string());\n}\n\nfn main() {\n    let mut s = String::new();\n    std::io::stdin().read_to_string(&mut s).unwrap();\n    let n: i64 = s.trim().parse().unwrap();\n    let mut recolectados: Vec<String> = Vec::new();\n    for i in 1..=n {\n        al_evento(&mut recolectados, i);\n    }\n    println!(\"eventos={}\", recolectados.join(\"-\"));\n}\n",
        "c": "#include <stdio.h>\n\nint main(void) {\n    long n;\n    if (scanf(\"%ld\", &n) != 1) return 1;\n    printf(\"eventos=\");\n    for (long i = 1; i <= n; i++) {\n        if (i > 1) printf(\"-\");\n        printf(\"%ld\", i);\n    }\n    printf(\"\\n\");\n    return 0;\n}\n",
        "php": "<?php\n$recolectados = [];\n$alEvento = function ($i) use (&$recolectados) {\n    $recolectados[] = $i;\n};\n\n$n = (int) trim(fgets(STDIN));\nfor ($i = 1; $i <= $n; $i++) {\n    $alEvento($i);\n}\necho \"eventos=\" . implode(\"-\", $recolectados) . \"\\n\";\n",
        "sql": "-- SQL no tiene eventos; se genera la secuencia con un CTE (ilustrativo, n=3).\nWITH RECURSIVE e(i) AS (VALUES (1) UNION ALL SELECT i + 1 FROM e WHERE i < 3)\nSELECT 'eventos=' || group_concat(i, '-') AS resultado FROM e;\n",
    },
}

S[120] = {
    "descripcion": "Procesar una lista como un flujo (stream): filtrar los pares y duplicarlos.",
    "objetivo": "Practicar el paradigma **reactivo / de flujos (streams)**: procesar datos como una corriente que pasa por operadores (filtrar, mapear) encadenados. Aquí un flujo filtra pares y los duplica.",
    "resultados": ["Encadenar operadores sobre un flujo.", "Filtrar y transformar en pipeline.", "Reconocer el estilo reactivo."],
    "temas": [("Flujo (stream)", "Datos como corriente"), ("Operadores encadenados", "filter, map, …"), ("Pipeline", "El dato fluye por pasos")],
    "definiciones": [("Flujo/stream", "secuencia de datos procesada por etapas. Clave: filter/map encadenados."), ("Operador", "etapa que transforma el flujo (filter, map). Clave: se encadenan."), ("Reactivo", "reaccionar a datos que llegan con el tiempo. Clave: streams y observables.")],
    "situacion": "Procesar eventos que llegan, filas de un archivo grande o mensajes en tiempo real: el estilo de flujos encadena operadores (filtrar → transformar) sin materializar todo a la vez.",
    "entrada": "una línea con enteros separados por espacio (al menos un par)",
    "salida": "`stream=<pares duplicados, unidos por ->`",
    "formula": "flujo: filtrar pares, luego map x → 2x",
    "algoritmo": "flujo(lista) |> filtrar(par) |> mapear(x->2x) |> recolectar",
    "casos": [("1 2 3 4", "stream=4-8"), ("2 4", "stream=4-8"), ("6 7 8", "stream=12-16")],
    "comparacion": [("Sintáctica", "`.filter().map()` (JS/Rust), Streams (Java), LINQ (C#), generadores (Python)."), ("Semántica", "Los operadores se encadenan; el dato fluye por el pipeline."), ("Paradigmática", "SQL encadena WHERE + SELECT, un pipeline declarativo.")],
    "familia": "En Java, la API Streams; en el frontend, RxJS y observables son puro estilo reactivo.",
    "errores": [("Materializar todo en cada paso", "gasto de memoria", "encadenar operadores perezosos cuando se pueda"), ("Orden de operadores equivocado", "resultado distinto", "filtrar antes de mapear si conviene")],
    "faq": [("¿Stream o bucle?", "El stream es más declarativo y componible; el bucle da control fino."), ("¿Reactivo es solo frontend?", "No: también backend (Reactor, Akka Streams) y procesamiento de datos.")],
    "reto": "Añade una etapa que sume el flujo al final (reduce) y resuélvelo en **Java** con Streams.",
    "impls": {
        "python": "import sys\n\nnums = [int(x) for x in sys.stdin.read().split()]\nstream = [x * 2 for x in nums if x % 2 == 0]\nprint(\"stream=\" + \"-\".join(str(x) for x in stream))\n",
        "javascript": "import { readFileSync } from \"node:fs\";\n\nconst nums = readFileSync(0, \"utf8\").trim().split(/\\s+/).map(Number);\nconst stream = nums.filter((x) => x % 2 === 0).map((x) => x * 2);\nconsole.log(`stream=${stream.join(\"-\")}`);\n",
        "typescript": "import { readFileSync } from \"node:fs\";\n\nconst nums: number[] = readFileSync(0, \"utf8\").trim().split(/\\s+/).map(Number);\nconst stream = nums.filter((x) => x % 2 === 0).map((x) => x * 2);\nconsole.log(`stream=${stream.join(\"-\")}`);\n",
        "java": "import java.io.BufferedReader;\nimport java.io.IOException;\nimport java.io.InputStreamReader;\nimport java.util.Arrays;\nimport java.util.stream.Collectors;\n\npublic class Main {\n    public static void main(String[] args) throws IOException {\n        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));\n        String[] p = br.readLine().trim().split(\"\\\\s+\");\n        String r = Arrays.stream(p).map(Integer::parseInt)\n                .filter(x -> x % 2 == 0).map(x -> x * 2)\n                .map(String::valueOf).collect(Collectors.joining(\"-\"));\n        System.out.println(\"stream=\" + r);\n    }\n}\n",
        "csharp": "using System;\nusing System.Linq;\n\nstring[] p = Console.In.ReadToEnd()\n    .Split(new[] { ' ', '\\t', '\\n', '\\r' }, StringSplitOptions.RemoveEmptyEntries);\nvar stream = p.Select(int.Parse).Where(x => x % 2 == 0).Select(x => x * 2);\nConsole.WriteLine($\"stream={string.Join(\"-\", stream)}\");\n",
        "go": "package main\n\nimport (\n\t\"bufio\"\n\t\"fmt\"\n\t\"os\"\n\t\"strconv\"\n\t\"strings\"\n)\n\nfunc main() {\n\tline, _ := bufio.NewReader(os.Stdin).ReadString('\\n')\n\tvar stream []string\n\tfor _, s := range strings.Fields(line) {\n\t\tn, _ := strconv.Atoi(s)\n\t\tif n%2 == 0 {\n\t\t\tstream = append(stream, strconv.Itoa(n*2))\n\t\t}\n\t}\n\tfmt.Printf(\"stream=%s\\n\", strings.Join(stream, \"-\"))\n}\n",
        "rust": "use std::io::Read;\n\nfn main() {\n    let mut s = String::new();\n    std::io::stdin().read_to_string(&mut s).unwrap();\n    let stream: Vec<String> = s\n        .split_whitespace()\n        .map(|x| x.parse::<i64>().unwrap())\n        .filter(|x| x % 2 == 0)\n        .map(|x| (x * 2).to_string())\n        .collect();\n    println!(\"stream={}\", stream.join(\"-\"));\n}\n",
        "c": "#include <stdio.h>\n\nint main(void) {\n    long x;\n    int primero = 1;\n    printf(\"stream=\");\n    while (scanf(\"%ld\", &x) == 1) {\n        if (x % 2 == 0) {\n            if (!primero) printf(\"-\");\n            printf(\"%ld\", x * 2);\n            primero = 0;\n        }\n    }\n    printf(\"\\n\");\n    return 0;\n}\n",
        "php": "<?php\n$nums = array_map('intval', preg_split('/\\s+/', trim(fgets(STDIN))));\n$stream = array_map(fn($x) => $x * 2, array_filter($nums, fn($x) => $x % 2 === 0));\necho \"stream=\" . implode(\"-\", $stream) . \"\\n\";\n",
        "sql": "-- SQL: WHERE + SELECT es un pipeline declarativo.\nWITH nums(x) AS (VALUES (1), (2), (3), (4))\nSELECT 'stream=' || group_concat(x * 2, '-') AS resultado FROM nums WHERE x % 2 = 0;\n",
    },
}

S[121] = {
    "descripcion": "Sumar una lista dividiendo el trabajo (visión concurrente); el resultado es la suma total.",
    "objetivo": "Asomarse al paradigma **concurrente**: hacer varias cosas a la vez con hilos, tareas o canales. Sumar una lista puede repartirse entre trabajadores; el resultado combinado es la suma total.",
    "resultados": ["Entender la idea de dividir el trabajo.", "Reconocer hilos, tareas y canales.", "Combinar resultados parciales."],
    "temas": [("Concurrencia", "Varias cosas a la vez"), ("Dividir y combinar", "Repartir el trabajo"), ("Hilos, tareas, canales", "Primitivas por lenguaje")],
    "definiciones": [("Concurrencia", "estructurar el programa como tareas que progresan a la vez. Clave: aprovecha varios núcleos."), ("Hilo/goroutine", "unidad de ejecución concurrente. Clave: comparte o no memoria según el modelo."), ("Combinar", "reunir los resultados parciales en el final. Clave: la suma total.")],
    "situacion": "Sumar millones de números, procesar imágenes o atender miles de conexiones: repartir el trabajo entre hilos o tareas aprovecha varios núcleos. El resultado combinado es el mismo, más rápido.",
    "entrada": "una línea con enteros separados por espacio",
    "salida": "`suma=<suma total>`",
    "formula": "repartir la lista, sumar por partes, combinar",
    "algoritmo": "dividir lista ; sumar cada parte (concurrente) ; combinar sumas",
    "casos": [("1 2 3 4", "suma=10"), ("5", "suma=5"), ("10 20 30", "suma=60")],
    "comparacion": [("Sintáctica", "hilos (Java/C#), goroutines+canales (Go), async (Rust), workers (JS)."), ("Semántica", "El resultado es determinista; el orden de ejecución no."), ("Paradigmática", "SQL delega el paralelismo al motor.")],
    "familia": "Go (CSP con goroutines/canales) y Erlang/Elixir (actores) son los referentes de la concurrencia segura.",
    "errores": [("Estado compartido sin sincronizar", "condiciones de carrera", "preferir mensajes o sumas parciales independientes"), ("Sobre-paralelizar tareas pequeñas", "el coste de coordinar supera la ganancia", "paralelizar solo cuando compensa")],
    "faq": [("¿Concurrencia = paralelismo?", "No exactamente: concurrencia es estructurar tareas; paralelismo es ejecutarlas a la vez."), ("¿El resultado cambia?", "El valor no; el orden de ejecución sí puede variar.")],
    "reto": "Suma dos mitades en dos hilos/goroutines reales y combínalas; resuélvelo en **Go**.",
    "impls": {
        "python": "import sys\n\nnums = [int(x) for x in sys.stdin.read().split()]\n# Visión concurrente: dividir en dos mitades y combinar.\nmedio = len(nums) // 2\nparcial1 = sum(nums[:medio])\nparcial2 = sum(nums[medio:])\nprint(f\"suma={parcial1 + parcial2}\")\n",
        "javascript": "import { readFileSync } from \"node:fs\";\n\nconst nums = readFileSync(0, \"utf8\").trim().split(/\\s+/).map(Number);\nconst medio = Math.floor(nums.length / 2);\nconst p1 = nums.slice(0, medio).reduce((a, b) => a + b, 0);\nconst p2 = nums.slice(medio).reduce((a, b) => a + b, 0);\nconsole.log(`suma=${p1 + p2}`);\n",
        "typescript": "import { readFileSync } from \"node:fs\";\n\nconst nums: number[] = readFileSync(0, \"utf8\").trim().split(/\\s+/).map(Number);\nconst medio = Math.floor(nums.length / 2);\nconst p1 = nums.slice(0, medio).reduce((a, b) => a + b, 0);\nconst p2 = nums.slice(medio).reduce((a, b) => a + b, 0);\nconsole.log(`suma=${p1 + p2}`);\n",
        "java": "import java.io.BufferedReader;\nimport java.io.IOException;\nimport java.io.InputStreamReader;\n\npublic class Main {\n    public static void main(String[] args) throws IOException {\n        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));\n        String[] p = br.readLine().trim().split(\"\\\\s+\");\n        int[] nums = new int[p.length];\n        for (int i = 0; i < p.length; i++) nums[i] = Integer.parseInt(p[i]);\n        int medio = nums.length / 2;\n        long p1 = 0, p2 = 0;\n        for (int i = 0; i < medio; i++) p1 += nums[i];\n        for (int i = medio; i < nums.length; i++) p2 += nums[i];\n        System.out.println(\"suma=\" + (p1 + p2));\n    }\n}\n",
        "csharp": "using System;\nusing System.Linq;\n\nint[] nums = Console.In.ReadToEnd()\n    .Split(new[] { ' ', '\\t', '\\n', '\\r' }, StringSplitOptions.RemoveEmptyEntries)\n    .Select(int.Parse).ToArray();\nint medio = nums.Length / 2;\nlong p1 = nums.Take(medio).Sum(x => (long) x);\nlong p2 = nums.Skip(medio).Sum(x => (long) x);\nConsole.WriteLine($\"suma={p1 + p2}\");\n",
        "go": "package main\n\nimport (\n\t\"bufio\"\n\t\"fmt\"\n\t\"os\"\n\t\"strconv\"\n\t\"strings\"\n)\n\nfunc main() {\n\tline, _ := bufio.NewReader(os.Stdin).ReadString('\\n')\n\tvar nums []int\n\tfor _, s := range strings.Fields(line) {\n\t\tn, _ := strconv.Atoi(s)\n\t\tnums = append(nums, n)\n\t}\n\tmedio := len(nums) / 2\n\tch := make(chan int, 2)\n\tsumar := func(parte []int) {\n\t\ts := 0\n\t\tfor _, x := range parte {\n\t\t\ts += x\n\t\t}\n\t\tch <- s\n\t}\n\tgo sumar(nums[:medio])\n\tgo sumar(nums[medio:])\n\ts1 := <-ch\n\ts2 := <-ch\n\tfmt.Printf(\"suma=%d\\n\", s1+s2)\n}\n",
        "rust": "use std::io::Read;\n\nfn main() {\n    let mut s = String::new();\n    std::io::stdin().read_to_string(&mut s).unwrap();\n    let nums: Vec<i64> = s.split_whitespace().map(|x| x.parse().unwrap()).collect();\n    let medio = nums.len() / 2;\n    let p1: i64 = nums[..medio].iter().sum();\n    let p2: i64 = nums[medio..].iter().sum();\n    println!(\"suma={}\", p1 + p2);\n}\n",
        "c": "#include <stdio.h>\n\nint main(void) {\n    long v[1024];\n    int n = 0;\n    while (scanf(\"%ld\", &v[n]) == 1) n++;\n    int medio = n / 2;\n    long p1 = 0, p2 = 0;\n    for (int i = 0; i < medio; i++) p1 += v[i];\n    for (int i = medio; i < n; i++) p2 += v[i];\n    printf(\"suma=%ld\\n\", p1 + p2);\n    return 0;\n}\n",
        "php": "<?php\n$nums = array_map('intval', preg_split('/\\s+/', trim(fgets(STDIN))));\n$medio = intdiv(count($nums), 2);\n$p1 = array_sum(array_slice($nums, 0, $medio));\n$p2 = array_sum(array_slice($nums, $medio));\necho \"suma=\" . ($p1 + $p2) . \"\\n\";\n",
        "sql": "-- SQL: el motor decide el paralelismo; aquí, SUM.\nWITH nums(x) AS (VALUES (1), (2), (3), (4))\nSELECT printf('suma=%d', sum(x)) AS resultado FROM nums;\n",
    },
}

S[122] = {
    "descripcion": "Obtener el doble de un número mediante una tarea asíncrona (async/await).",
    "objetivo": "Asomarse al paradigma **asíncrono**: iniciar una operación que tardará y continuar sin bloquear, esperando su resultado con `async/await`. Aquí una tarea calcula el doble y se espera su valor.",
    "resultados": ["Definir y esperar una tarea asíncrona.", "Explicar por qué no bloquea.", "Reconocer async/await por lenguaje."],
    "temas": [("Asíncrono", "No bloquear mientras se espera"), ("async/await", "Esperar sin bloquear el hilo"), ("Tarea/promesa/future", "El resultado que llegará")],
    "definiciones": [("Asíncrono", "iniciar algo que tarda y seguir sin bloquear. Clave: eficiente para I/O."), ("async/await", "sintaxis para escribir código asíncrono como si fuera secuencial. Clave: legible."), ("Promesa/Future/Task", "objeto que representa un resultado futuro. Clave: se espera con await.")],
    "situacion": "Leer de la red, de disco o de una base de datos tarda. En vez de bloquear el hilo, `async/await` inicia la operación y continúa, esperando el resultado cuando llega. Clave en servidores y UI.",
    "entrada": "un entero `n`",
    "salida": "`resultado=<2n>`",
    "formula": "await doble(n) = 2n",
    "algoritmo": "async doble(x): DEVOLVER 2x ; resultado <- await doble(n)",
    "casos": [("5", "resultado=10"), ("0", "resultado=0"), ("6", "resultado=12")],
    "comparacion": [("Sintáctica", "`async/await` (JS/TS/Python/C#/Rust), goroutines+canales (Go)."), ("Semántica", "await no bloquea el hilo; libera para otras tareas."), ("Paradigmática", "SQL no tiene async a nivel de lenguaje.")],
    "familia": "JavaScript popularizó async/await; hoy está en Python, C#, Rust y otros. Go usa goroutines en su lugar.",
    "errores": [("Bloquear en vez de esperar", "desperdiciar la ventaja asíncrona", "usar await, no una espera activa"), ("Olvidar await", "obtener la promesa, no el valor", "esperar el resultado antes de usarlo")],
    "faq": [("¿Async es paralelismo?", "No: es no bloquear mientras se espera; puede usar un solo hilo."), ("¿Y Go?", "Usa goroutines y canales en lugar de async/await, con un modelo distinto.")],
    "reto": "Espera dos tareas asíncronas y suma sus resultados; resuélvelo en **JavaScript** con `Promise.all`.",
    "impls": {
        "python": "import sys\nimport asyncio\n\n\nasync def doble(x):\n    return x * 2\n\n\nasync def main():\n    n = int(sys.stdin.readline())\n    resultado = await doble(n)\n    print(f\"resultado={resultado}\")\n\n\nasyncio.run(main())\n",
        "javascript": "import { readFileSync } from \"node:fs\";\n\nasync function doble(x) {\n  return x * 2;\n}\n\nconst n = parseInt(readFileSync(0, \"utf8\").trim(), 10);\n(async () => {\n  const resultado = await doble(n);\n  console.log(`resultado=${resultado}`);\n})();\n",
        "typescript": "import { readFileSync } from \"node:fs\";\n\nasync function doble(x: number): Promise<number> {\n  return x * 2;\n}\n\nconst n: number = parseInt(readFileSync(0, \"utf8\").trim(), 10);\n(async () => {\n  const resultado: number = await doble(n);\n  console.log(`resultado=${resultado}`);\n})();\n",
        "java": "import java.io.BufferedReader;\nimport java.io.IOException;\nimport java.io.InputStreamReader;\nimport java.util.concurrent.CompletableFuture;\nimport java.util.concurrent.ExecutionException;\n\npublic class Main {\n    public static void main(String[] args) throws IOException, InterruptedException, ExecutionException {\n        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));\n        int n = Integer.parseInt(br.readLine().trim());\n        CompletableFuture<Integer> tarea = CompletableFuture.supplyAsync(() -> n * 2);\n        System.out.println(\"resultado=\" + tarea.get());\n    }\n}\n",
        "csharp": "using System;\nusing System.Threading.Tasks;\n\nasync Task<int> Doble(int x) => await Task.FromResult(x * 2);\n\nint n = int.Parse(Console.In.ReadToEnd().Trim());\nint resultado = await Doble(n);\nConsole.WriteLine($\"resultado={resultado}\");\n",
        "go": "package main\n\nimport (\n\t\"bufio\"\n\t\"fmt\"\n\t\"os\"\n\t\"strconv\"\n\t\"strings\"\n)\n\nfunc main() {\n\tline, _ := bufio.NewReader(os.Stdin).ReadString('\\n')\n\tn, _ := strconv.Atoi(strings.TrimSpace(line))\n\t// Go usa goroutines y canales en lugar de async/await.\n\tch := make(chan int, 1)\n\tgo func() { ch <- n * 2 }()\n\tfmt.Printf(\"resultado=%d\\n\", <-ch)\n}\n",
        "rust": "use std::io::Read;\n\nfn main() {\n    let mut s = String::new();\n    std::io::stdin().read_to_string(&mut s).unwrap();\n    let n: i64 = s.trim().parse().unwrap();\n    // Sin runtime async externo, se muestra el resultado de la tarea.\n    let resultado = n * 2;\n    println!(\"resultado={resultado}\");\n}\n",
        "c": "#include <stdio.h>\n\nint main(void) {\n    long n;\n    if (scanf(\"%ld\", &n) != 1) return 1;\n    /* C no tiene async a nivel de lenguaje; se calcula el resultado. */\n    printf(\"resultado=%ld\\n\", n * 2);\n    return 0;\n}\n",
        "php": "<?php\n$n = (int) trim(fgets(STDIN));\n// PHP es síncrono por defecto; se muestra el resultado de la tarea.\necho \"resultado=\" . ($n * 2) . \"\\n\";\n",
        "sql": "-- SQL no tiene async a nivel de lenguaje.\nWITH nums(n) AS (VALUES (5), (0), (6))\nSELECT printf('resultado=%d', n * 2) AS resultado FROM nums;\n",
    },
}


def main():
    for num, spec in S.items():
        g3.write_class(num, spec)
        print(f"Clase {num:03d} generada.")


if __name__ == "__main__":
    main()
